In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

In [31]:
dtypes_data = {'GAME_ID':str, 'EVENTNUM':'int16', 'EVENTMSGTYPE':'int16', 'EVENTMSGACTIONTYPE':'int16', 'PERIOD':'int16', 'PERSON1TYPE':int, 'PLAYER1_ID':int,
'PERSON2TYPE':int, 'PLAYER2_ID':int, 'PERSON3TYPE':int, 'PLAYER3_ID':int, "game_time_s":'int16', 'game_time_left':'int16', 
'stint':'int16', 'POSS_CHANGE':'int16', 'TEAM_LOCATION':'category', 'GAME_ID':'category', 'AWAY_POSS':'float32'
              , 'HOME_POSS':'float32', 'HOME_PM':'float32', 'AWAY_PM':'float32'}

col_select_data = ['GAME_ID', 'EVENTMSGTYPE', 'SCORE', 'PLAYER1_ID', 'TEAM_LOCATION', 'stint', 
                   'POSS_CHANGE', 'AWAY_POSS', 'HOME_POSS', 'HOME_PTS', 'AWAY_PTS', 'HOME_PM', 'AWAY_PM',
                  'HOME_PM_100', 'AWAY_PM_100']
col_select_subs = ['GAME_ID', 'stint', 'TEAM_LOCATION', 'PLAYER_OUT_ID', 'PLAYER_IN_ID']
col_select_starters = ['GAME_ID', 'PLAYER_ID', 'TEAM_ID', 'TEAM_LOCATION', 'START_POSITION',]

dtypes_subs = {'GAME_ID':str, 'stint':int, 'game_time_left':int, 'PLAYER_OUT_ID':int, 'PLAYER_IN_ID':int}
dtypes_starters = {'GAME_ID':str, 'TEAM_ID':int, 'STARTER':bool}

dtypes_dummy = {'GAME_ID':'category', 'stint':'int16', 'variable':'category'}

In [40]:
subs = pd.read_csv("subs.csv", dtype=dtypes_subs, usecols=col_select_subs)
starters = pd.read_csv("starters.csv", dtype=dtypes_starters, usecols=col_select_starters)
data = pd.read_csv("preprocessing.csv", dtype=dtypes_data, usecols=col_select_data)

In [337]:
dummy = pd.read_csv("dummy_matrix_test.csv")

In [339]:
np_dummy = dummy.to_numpy()

In [356]:
np_dummy[0, 4:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0], dtype=object)

In [350]:
(np_dummy[:, 4:] == 1).sum()

131142

In [91]:
tmp_df = pd.read_csv("raw_dummy.csv", nrows=1)
tmp = tmp_df.columns

# get keys
keys_tmp = tmp.to_list()
keys = keys_tmp[1:]

# generate dtypes values
values = ['category', 'int8', 'category']
int_values = ['int8'] * len(keys)
values.extend(int_values)

# create dtype dictionary
dtypes_dummy = dict(zip(keys, values))

In [166]:
dummy = pd.read_csv("raw_dummy.csv", nrows=1000, dtype=dtypes_dummy, usecols=keys)
test = dummy.groupby(['GAME_ID', 'stint']).sum().reset_index()

In [171]:
players = pd.read_csv("playercareerstats.csv")

In [224]:
player_ids = players['PLAYER_ID'].unique().tolist()
player_ids = np.asarray(player_ids).reshape(1, -1)

In [245]:
test = dummy.groupby(['GAME_ID', 'stint']).sum().reset_index()
test.iloc[:, 2:].sum(axis=1)

0      14
1       1
2      10
3       1
4       2
       ..
178     0
179     0
180     0
181     0
182     0
Length: 183, dtype: int64

In [228]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories=np.sort(player_ids), handle_unknown='ignore', sparse=False)

In [229]:
ohe

OneHotEncoder(categories=array([[   2544,    2546,    2617,    2730,    2738,    2772,  101108,
         101150,  200746,  200752,  200765,  200768,  200782,  200794,
         201142,  201143,  201144,  201145,  201152,  201565,  201566,
         201567,  201568,  201569,  201571,  201572,  201577,  201580,
         201586,  201587,  201588,  201599,  201609,  201933,  201935,
         201937,  201939,  201942,  201949,  201950,  201959,  201961,
         201976,  201980,  201988,  202066,  202322,...
        1630180, 1630181, 1630182, 1630183, 1630184, 1630186, 1630188,
        1630190, 1630191, 1630192, 1630193, 1630194, 1630197, 1630198,
        1630200, 1630201, 1630202, 1630203, 1630205, 1630206, 1630208,
        1630209, 1630210, 1630214, 1630216, 1630217, 1630218, 1630219,
        1630230, 1630231, 1630233, 1630235, 1630238, 1630240, 1630241,
        1630256, 1630264, 1630267, 1630271, 1630466]]),
              handle_unknown='ignore', sparse=False)

In [230]:
positions = ["GUARD_1_HOME", "GUARD_2_HOME", "FORWARD_1_HOME", "FORWARD_2_HOME", "CENTER_1_HOME", "GUARD_1_AWAY", "GUARD_2_AWAY", "FORWARD_1_AWAY", "FORWARD_2_AWAY", "CENTER_1_AWAY"]
list_ohe = list()

for pos in positions:
    list_ohe.append(ohe.fit_transform(on_court[pos].values.reshape(-1,1)))

/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:80: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories != 'auto':
/Users/hoener/opt/anaconda3/envs/ds/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.categories == 'auto':

In [234]:
arr = np.zeros(list_ohe[0].shape)
for l in list_ohe:
    arr += l

In [302]:
on_court = pd.read_csv("on_court.csv")

- read in on_court
- melt on_court
- get dummies from value column

In [303]:
on_court

,Unnamed: 0,GUARD_1_HOME,GUARD_2_HOME,FORWARD_1_HOME,FORWARD_2_HOME,CENTER_1_HOME,GUARD_1_AWAY,GUARD_2_AWAY,FORWARD_1_AWAY,FORWARD_2_AWAY,CENTER_1_AWAY,stint,GAME_ID
0,0,1628971.0,1627789.0,1629066.0,1629066.0,204020.0,201939.0,201939.0,203145.0,1627814.0,203145.0,1,22000001
1,1,1628971.0,1627789.0,1629066.0,1629066.0,204020.0,201939.0,201939.0,203145.0,1627814.0,203145.0,2,22000001
2,2,1628971.0,1627789.0,1629066.0,1629066.0,204020.0,201939.0,201939.0,203145.0,1627814.0,203145.0,3,22000001
3,3,1628971.0,1627789.0,1629066.0,1629066.0,204020.0,201939.0,201939.0,203145.0,1627814.0,203145.0,4,22000001
4,4,1628971.0,1627789.0,1629066.0,1629066.0,204020.0,201939.0,201939.0,203145.0,1627814.0,203145.0,5,22000001
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49359,47,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,48,22001080
49360,48,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,49,22001080
49361,49,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,50,22001080
49362,50,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,51,22001080
49363,51,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,52,22001080

In [304]:
test = pd.melt(on_court, id_vars=['GAME_ID', 'stint'], value_vars=["GUARD_1_HOME", "GUARD_2_HOME", "FORWARD_1_HOME", "FORWARD_2_HOME", "CENTER_1_HOME", "GUARD_1_AWAY", "GUARD_2_AWAY", "FORWARD_1_AWAY", "FORWARD_2_AWAY", "CENTER_1_AWAY"])

In [305]:
test

         GAME_ID  stint       variable      value
0       22000001      1   GUARD_1_HOME  1628971.0
1       22000001      2   GUARD_1_HOME  1628971.0
2       22000001      3   GUARD_1_HOME  1628971.0
3       22000001      4   GUARD_1_HOME  1628971.0
4       22000001      5   GUARD_1_HOME  1628971.0
...          ...    ...            ...        ...
493635  22001080     48  CENTER_1_AWAY  1626179.0
493636  22001080     49  CENTER_1_AWAY  1626179.0
493637  22001080     50  CENTER_1_AWAY  1626179.0
493638  22001080     51  CENTER_1_AWAY  1626179.0
493639  22001080     52  CENTER_1_AWAY  1626179.0

[493640 rows x 4 columns]

In [306]:
test2 = pd.get_dummies(test, columns=['value'])

In [307]:
list_away = ["GUARD_1_AWAY", "GUARD_2_AWAY", "FORWARD_1_AWAY", "FORWARD_2_AWAY", "CENTER_1_AWAY"]

In [308]:
test2

,GAME_ID,stint,variable,value_2544.0,value_2546.0,value_2730.0,value_2738.0,value_2760.0,value_2772.0,value_101108.0,...,value_1630241.0,value_1630253.0,value_1630256.0,value_1630264.0,value_1630266.0,value_1630267.0,value_1630268.0,value_1630271.0,value_1630273.0,value_1630466.0
0,22000001,1,GUARD_1_HOME,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,22000001,2,GUARD_1_HOME,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,22000001,3,GUARD_1_HOME,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22000001,4,GUARD_1_HOME,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,22000001,5,GUARD_1_HOME,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493635,22001080,48,CENTER_1_AWAY,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
493636,22001080,49,CENTER_1_AWAY,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
493637,22001080,50,CENTER_1_AWAY,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
493638,22001080,51,CENTER_1_AWAY,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
493639,22001080,52,CENTER_1_AWAY,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [310]:
colnames = test2.columns.to_list()
arr_data = test2.to_numpy()

In [312]:
bool_away = test2['variable'].isin(list_away)
vec_away = np.where(bool_away, -1, 1)

In [327]:
arr_data[:, 3:]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [333]:
arr_data[:, 3:] = arr_data[:, 3:] * vec_away.reshape(-1, 1)

In [293]:
tmp_a = test2.iloc[:, 3:].to_numpy()
tmp_stem = test2.iloc[:, :3].to_numpy()
col_names = test2.columns.to_list()

In [334]:
test2b = pd.DataFrame(arr_data, columns=colnames)

In [336]:
test3 = test2b.groupby(['GAME_ID', 'stint']).sum().reset_index()

KeyboardInterrupt:

In [ ]:
test3.iloc[:, 2:].sum(axis=1)

In [151]:
cols_positions = on_court.iloc[:, 1:11].columns.to_list()

In [152]:
tmp = pd.get_dummies(on_court, columns=cols_positions)

In [153]:
tmp.iloc[:, 3:].sum(axis=1)

0        10
1        10
2        10
3        10
4        10
         ..
49359    10
49360    10
49361    10
49362    10
49363    10
Length: 49364, dtype: int64

In [154]:
tmp.shape

(49364, 4209)

In [158]:
tmp.columns.unique()

Index(['Unnamed: 0', 'stint', 'GAME_ID', 'GUARD_1_HOME_2544.0',
       'GUARD_1_HOME_2546.0', 'GUARD_1_HOME_2738.0', 'GUARD_1_HOME_2760.0',
       'GUARD_1_HOME_2772.0', 'GUARD_1_HOME_101108.0', 'GUARD_1_HOME_101150.0',
       ...
       'CENTER_1_AWAY_1630234.0', 'CENTER_1_AWAY_1630237.0',
       'CENTER_1_AWAY_1630238.0', 'CENTER_1_AWAY_1630240.0',
       'CENTER_1_AWAY_1630253.0', 'CENTER_1_AWAY_1630256.0',
       'CENTER_1_AWAY_1630264.0', 'CENTER_1_AWAY_1630267.0',
       'CENTER_1_AWAY_1630271.0', 'CENTER_1_AWAY_1630273.0'],
      dtype='object', length=4209)

In [121]:
(dummy.iloc[0, 3:] == -1).sum()

0

In [111]:
dummy = pd.read_csv("raw_dummy.csv", usecols=['stint'])
dummy

         stint
0            1
1            1
2            1
3            1
4            1
...        ...
4368515     39
4368516     39
4368517     39
4368518     39
4368519     39

[4368520 rows x 1 columns]

In [ ]:
# dummy shape 4368520 x 536 ~ 2150 mb

In [109]:
col_select_scores = ['GAME_ID', 'stint', 'HOME_PTS', 'AWAY_PTS', 'HOME_PM', 'HOME_PM_100']
dtypes_scores = {'GAME_ID':'category', 'stint':'int8'}

scores = pd.read_csv("raw_scores.csv", dtype=dtypes_scores, usecols=col_select_scores)

In [110]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436852 entries, 0 to 436851
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   GAME_ID      436852 non-null  category
 1   stint        436852 non-null  int8
 2   HOME_PTS     436852 non-null  float64
 3   AWAY_PTS     436852 non-null  float64
 4   HOME_PM      436852 non-null  float64
 5   HOME_PM_100  427693 non-null  float64
dtypes: category(1), float64(4), int8(1)
memory usage: 14.6 MB

In [103]:
dummy.memory_usage(deep=True)

Index            128
GAME_ID      2105022
stint        1000000
variable     1000317
2544.0       1000000
              ...
1630267.0    1000000
1630268.0    1000000
1630271.0    1000000
1630273.0    1000000
1630466.0    1000000
Length: 537, dtype: int64

In [104]:
dummy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Columns: 536 entries, GAME_ID to 1630466.0
dtypes: category(2), int8(534)
memory usage: 512.2 MB

In [369]:
data.memory_usage(deep=True)

Index                 128
GAME_ID           3430922
EVENTMSGTYPE      3073474
SCORE            64248655
PLAYER1_ID       12293896
TEAM_LOCATION     1537025
stint             3073474
POSS_CHANGE       3073474
AWAY_POSS         6146948
HOME_POSS         6146948
HOME_PTS         12293896
AWAY_PTS         12293896
HOME_PM           6146948
AWAY_PM           6146948
HOME_PM_100      12293896
AWAY_PM_100      12293896
dtype: int64

In [370]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1536737 entries, 0 to 1536736
Data columns (total 15 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   GAME_ID        1536737 non-null  category
 1   EVENTMSGTYPE   1536737 non-null  int16
 2   SCORE          495134 non-null   object
 3   PLAYER1_ID     1536737 non-null  int64
 4   TEAM_LOCATION  1462128 non-null  category
 5   stint          1536737 non-null  int16
 6   POSS_CHANGE    1536737 non-null  int16
 7   AWAY_POSS      1346696 non-null  float32
 8   HOME_POSS      1366470 non-null  float32
 9   HOME_PTS       1536678 non-null  float64
 10  AWAY_PTS       1536678 non-null  float64
 11  HOME_PM        1536678 non-null  float32
 12  AWAY_PM        1536678 non-null  float32
 13  HOME_PM_100    1364269 non-null  float64
 14  AWAY_PM_100    1345280 non-null  float64
dtypes: category(2), float32(4), float64(4), int16(3), int64(1), object(1)
memory usage: 107.1+ MB

In [304]:
df_schedule = pd.read_csv("./data/season_prediction/schedule.csv", dtype={'GAME_ID':str})

In [319]:
df_schedule[df_schedule['SEASON_ID'] == 22017]['GAME_ID'].to_csv('game_ids_2017.csv')

['0021700002',
 '0021700002',
 '0021700001',
 '0021700001',
 '0021700011',
 '0021700011',
 '0021700012',
 '0021700012',
 '0021700007',
 '0021700007',
 '0021700005',
 '0021700005',
 '0021700003',
 '0021700003',
 '0021700004',
 '0021700004',
 '0021700010',
 '0021700010',
 '0021700009',
 '0021700009',
 '0021700013',
 '0021700013',
 '0021700006',
 '0021700006',
 '0021700008',
 '0021700008',
 '0021700016',
 '0021700016',
 '0021700014',
 '0021700014',
 '0021700015',
 '0021700015',
 '0021700019',
 '0021700019',
 '0021700026',
 '0021700026',
 '0021700022',
 '0021700022',
 '0021700021',
 '0021700021',
 '0021700018',
 '0021700018',
 '0021700024',
 '0021700024',
 '0021700023',
 '0021700023',
 '0021700017',
 '0021700017',
 '0021700020',
 '0021700020',
 '0021700025',
 '0021700025',
 '0021700031',
 '0021700031',
 '0021700030',
 '0021700030',
 '0021700037',
 '0021700037',
 '0021700032',
 '0021700032',
 '0021700028',
 '0021700028',
 '0021700029',
 '0021700029',
 '0021700034',
 '0021700034',
 '0021700036',
 '0021700036',
 '0021700035',
 '0021700035',
 '0021700027',
 '0021700027',
 '0021700033',
 '0021700033',
 '0021700040',
 '0021700040',
 '0021700038',
 '0021700038',
 '0021700039',
 '0021700039',
 '0021700046',
 '0021700046',
 '0021700048',
 '0021700048',
 '0021700043',
 '0021700043',
 '0021700042',
 '0021700042',
 '0021700041',
 '0021700041',
 '0021700044',
 '0021700044',
 '0021700045',
 '0021700045',
 '0021700047',
 '0021700047',
 '0021700051',
 '0021700051',
 '0021700054',
 '0021700054',
 '0021700050',
 '0021700050',
 '0021700049',
 '0021700049',
 '0021700053',
 '0021700053',
 '0021700052',
 '0021700052',
 '0021700057',
 '0021700057',
 '0021700063',
 '0021700063',
 '0021700064',
 '0021700064',
 '0021700062',
 '0021700062',
 '0021700058',
 '0021700058',
 '0021700059',
 '0021700059',
 '0021700056',
 '0021700056',
 '0021700061',
 '0021700061',
 '0021700055',
 '0021700055',
 '0021700060',
 '0021700060',
 '0021700065',
 '0021700065',
 '0021700068',
 '0021700068',
 '0021700067',
 '0021700067',
 '0021700069',
 '0021700069',
 '0021700066',
 '0021700066',
 '0021700075',
 '0021700075',
 '0021700076',
 '0021700076',
 '0021700073',
 '0021700073',
 '0021700071',
 '0021700071',
 '0021700072',
 '0021700072',
 '0021700074',
 '0021700074',
 '0021700070',
 '0021700070',
 '0021700079',
 '0021700079',
 '0021700084',
 '0021700084',
 '0021700078',
 '0021700078',
 '0021700083',
 '0021700083',
 '0021700082',
 '0021700082',
 '0021700081',
 '0021700081',
 '0021700080',
 '0021700080',
 '0021700077',
 '0021700077',
 '0021700091',
 '0021700091',
 '0021700087',
 '0021700087',
 '0021700090',
 '0021700090',
 '0021700085',
 '0021700085',
 '0021700086',
 '0021700086',
 '0021700089',
 '0021700089',
 '0021700088',
 '0021700088',
 '0021700094',
 '0021700094',
 '0021700092',
 '0021700092',
 '0021700100',
 '0021700100',
 '0021700095',
 '0021700095',
 '0021700093',
 '0021700093',
 '0021700099',
 '0021700099',
 '0021700098',
 '0021700098',
 '0021700096',
 '0021700096',
 '0021700097',
 '0021700097',
 '0021700104',
 '0021700104',
 '0021700102',
 '0021700102',
 '0021700103',
 '0021700103',
 '0021700101',
 '0021700101',
 '0021700107',
 '0021700107',
 '0021700111',
 '0021700111',
 '0021700109',
 '0021700109',
 '0021700116',
 '0021700116',
 '0021700106',
 '0021700106',
 '0021700110',
 '0021700110',
 '0021700115',
 '0021700115',
 '0021700114',
 '0021700114',
 '0021700105',
 '0021700105',
 '0021700108',
 '0021700108',
 '0021700112',
 '0021700112',
 '0021700113',
 '0021700113',
 '0021700117',
 '0021700117',
 '0021700118',
 '0021700118',
 '0021700121',
 '0021700121',
 '0021700126',
 '0021700126',
 '0021700130',
 '0021700130',
 '0021700124',
 '0021700124',
 '0021700120',
 '0021700120',
 '0021700119',
 '0021700119',
 '0021700128',
 '0021700128',
 '0021700123',
 '0021700123',
 '0021700125',
 '0021700125',
 '0021700127',
 '0021700127',
 '0021700122',
 '0021700122',
 '0021700129',
 '0021700129',
 '0021700133',
 '0021700133',
 '0021700131',
 '0021700131',
 '0021700132',
 '0021700132',
 '0021700135',
 '0021700135',
 '0021700134',
 '0021700134',
 '0021700141',
 '0021700141',
 '0021700145',
 '0021700145',
 '0021700142',
 '0021700142',
 '0021700137',
 '0021700137',
 '0021700138',
 '0021700138',
 '0021700140',
 '0021700140',
 '0021700136',
 '0021700136',
 '0021700144',
 '0021700144',
 '0021700143',
 '0021700143',
 '0021700139',
 '0021700139',
 '0021700148',
 '0021700148',
 '0021700147',
 '0021700147',
 '0021700146',
 '0021700146',
 '0021700154',
 '0021700154',
 '0021700152',
 '0021700152',
 '0021700149',
 '0021700149',
 '0021700157',
 '0021700157',
 '0021700156',
 '0021700156',
 '0021700150',
 '0021700150',
 '0021700158',
 '0021700158',
 '0021700155',
 '0021700155',
 '0021700151',
 '0021700151',
 '0021700153',
 '0021700153',
 '0021700163',
 '0021700163',
 '0021700162',
 '0021700162',
 '0021700161',
 '0021700161',
 '0021700160',
 '0021700160',
 '0021700159',
 '0021700159',
 '0021700166',
 '0021700166',
 '0021700167',
 '0021700167',
 '0021700168',
 '0021700168',
 '0021700164',
 '0021700164',
 '0021700165',
 '0021700165',
 '0021700173',
 '0021700173',
 '0021700171',
 '0021700171',
 '0021700174',
 '0021700174',
 '0021700170',
 '0021700170',
 '0021700169',
 '0021700169',
 '0021700176',
 '0021700176',
 '0021700175',
 '0021700175',
 '0021700172',
 '0021700172',
 '0021700184',
 '0021700184',
 '0021700183',
 '0021700183',
 '0021700179',
 '0021700179',
 '0021700186',
 '0021700186',
 '0021700180',
 '0021700180',
 '0021700182',
 '0021700182',
 '0021700187',
 '0021700187',
 '0021700181',
 '0021700181',
 '0021700185',
 '0021700185',
 '0021700177',
 '0021700177',
 '0021700178',
 '0021700178',
 '0021700188',
 '0021700188',
 '0021700189',
 '0021700189',
 '0021700190',
 '0021700190',
 '0021700191',
 '0021700191',
 '0021700199',
 '0021700199',
 '0021700193',
 '0021700193',
 '0021700196',
 '0021700196',
 '0021700200',
 '0021700200',
 '0021700198',
 '0021700198',
 '0021700194',
 '0021700194',
 '0021700197',
 '0021700197',
 '0021700192',
 '0021700192',
 '0021700195',
 '0021700195',
 '0021700201',
 '0021700201',
 '0021700202',
 '0021700202',
 '0021700203',
 '0021700203',
 '0021700211',
 '0021700211',
 '0021700214',
 '0021700214',
 '0021700206',
 '0021700206',
 '0021700205',
 '0021700205',
 '0021700213',
 '0021700213',
 '0021700209',
 '0021700209',
 '0021700204',
 '0021700204',
 '0021700207',
 '0021700207',
 '0021700210',
 '0021700210',
 '0021700212',
 '0021700212',
 '0021700208',
 '0021700208',
 '0021700216',
 '0021700216',
 '0021700215',
 '0021700215',
 '0021700223',
 '0021700223',
 '0021700227',
 '0021700227',
 '0021700222',
 '0021700222',
 '0021700219',
 '0021700219',
 '0021700220',
 '0021700220',
 '0021700217',
 '0021700217',
 '0021700224',
 '0021700224',
 '0021700225',
 '0021700225',
 '0021700226',
 '0021700226',
 '0021700218',
 '0021700218',
 '0021700221',
 '0021700221',
 '0021700231',
 '0021700231',
 '0021700229',
 '0021700229',
 '0021700234',
 '0021700234',
 '0021700230',
 '0021700230',
 '0021700233',
 '0021700233',
 '0021700228',
 '0021700228',
 '0021700232',
 '0021700232',
 '0021700240',
 '0021700240',
 '0021700239',
 '0021700239',
 '0021700236',
 '0021700236',
 '0021700235',
 '0021700235',
 '0021700238',
 '0021700238',
 '0021700237',
 '0021700237',
 '0021700244',
 '0021700244',
 '0021700250',
 '0021700250',
 '0021700245',
 '0021700245',
 '0021700243',
 '0021700243',
 '0021700242',
 '0021700242',
 '0021700247',
 '0021700247',
 '0021700249',
 '0021700249',
 '0021700251',
 '0021700251',
 '0021700241',
 '0021700241',
 '0021700246',
 '0021700246',
 '0021700248',
 '0021700248',
 '0021700252',
 '0021700252',
 '0021700255',
 '0021700255',
 '0021700258',
 '0021700258',
 '0021700264',
 '0021700264',
 '0021700259',
 '0021700259',
 '0021700254',
 '0021700254',
 '0021700257',
 '0021700257',
 '0021700265',
 '0021700265',
 '0021700256',
 '0021700256',
 '0021700266',
 '0021700266',
 '0021700261',
 '0021700261',
 '0021700253',
 '0021700253',
 '0021700263',
 '0021700263',
 '0021700260',
 '0021700260',
 '0021700262',
 '0021700262',
 '0021700276',
 '0021700276',
 '0021700275',
 '0021700275',
 '0021700267',
 '0021700267',
 '0021700269',
 '0021700269',
 '0021700270',
 '0021700270',
 '0021700271',
 '0021700271',
 '0021700268',
 '0021700268',
 '0021700274',
 '0021700274',
 '0021700272',
 '0021700272',
 '0021700273',
 '0021700273',
 '0021700278',
 '0021700278',
 '0021700284',
 '0021700284',
 '0021700282',
 '0021700282',
 '0021700285',
 '0021700285',
 '0021700281',
 '0021700281',
 '0021700280',
 '0021700280',
 '0021700283',
 '0021700283',
 '0021700286',
 '0021700286',
 '0021700277',
 '0021700277',
 '0021700279',
 '0021700279',
 '0021700287',
 '0021700287',
 '0021700288',
 '0021700288',
 '0021700289',
 '0021700289',
 '0021700291',
 '0021700291',
 '0021700296',
 '0021700296',
 '0021700295',
 '0021700295',
 '0021700293',
 '0021700293',
 '0021700292',
 '0021700292',
 '0021700297',
 '0021700297',
 '0021700294',
 '0021700294',
 '0021700290',
 '0021700290',
 '0021700299',
 '0021700299',
 '0021700298',
 '0021700298',
 '0021700301',
 '0021700301',
 '0021700302',
 '0021700302',
 '0021700300',
 '0021700300',
 '0021700305',
 '0021700305',
 '0021700311',
 '0021700311',
 '0021700312',
 '0021700312',
 '0021700306',
 '0021700306',
 '0021700304',
 '0021700304',
 '0021700308',
 '0021700308',
 '0021700303',
 '0021700303',
 '0021700310',
 '0021700310',
 '0021700307',
 '0021700307',
 '0021700309',
 '0021700309',
 '0021700314',
 '0021700314',
 '0021700317',
 '0021700317',
 '0021700316',
 '0021700316',
 '0021700313',
 '0021700313',
 '0021700315',
 '0021700315',
 '0021700322',
 '0021700322',
 '0021700318',
 '0021700318',
 '0021700321',
 '0021700321',
 '0021700325',
 '0021700325',
 '0021700320',
 '0021700320',
 '0021700319',
 '0021700319',
 '0021700324',
 '0021700324',
 '0021700323',
 '0021700323',
 '0021700330',
 '0021700330',
 '0021700328',
 '0021700328',
 '0021700326',
 '0021700326',
 '0021700329',
 '0021700329',
 '0021700333',
 '0021700333',
 '0021700331',
 '0021700331',
 '0021700327',
 '0021700327',
 '0021700332',
 '0021700332',
 '0021700338',
 '0021700338',
 '0021700334',
 '0021700334',
 '0021700335',
 '0021700335',
 '0021700336',
 '0021700336',
 '0021700337',
 '0021700337',
 '0021700341',
 '0021700341',
 '0021700348',
 '0021700348',
 '0021700344',
 '0021700344',
 '0021700343',
 '0021700343',
 '0021700349',
 '0021700349',
 '0021700340',
 '0021700340',
 '0021700342',
 '0021700342',
 '0021700347',
 '0021700347',
 '0021700339',
 '0021700339',
 '0021700345',
 '0021700345',
 '0021700346',
 '0021700346',
 '0021700352',
 '0021700352',
 '0021700350',
 '0021700350',
 '0021700351',
 '0021700351',
 '0021700361',
 '0021700361',
 '0021700357',
 '0021700357',
 '0021700356',
 '0021700356',
 '0021700362',
 '0021700362',
 '0021700355',
 '0021700355',
 '0021700353',
 '0021700353',
 '0021700359',
 '0021700359',
 '0021700354',
 '0021700354',
 '0021700358',
 '0021700358',
 '0021700360',
 '0021700360',
 '0021700363',
 '0021700363',
 '0021700364',
 '0021700364',
 '0021700365',
 '0021700365',
 '0021700366',
 '0021700366',
 '0021700374',
 '0021700374',
 '0021700370',
 '0021700370',
 '0021700368',
 '0021700368',
 '0021700372',
 '0021700372',
 '0021700369',
 '0021700369',
 '0021700367',
 '0021700367',
 '0021700371',
 '0021700371',
 '0021700373',
 '0021700373',
 '0021700380',
 '0021700380',
 '0021700383',
 '0021700383',
 '0021700376',
 '0021700376',
 '0021700375',
 '0021700375',
 '0021700379',
 '0021700379',
 '0021700384',
 '0021700384',
 '0021700381',
 '0021700381',
 '0021700378',
 '0021700378',
 '0021700377',
 '0021700377',
 '0021700382',
 '0021700382',
 '0021700390',
 '0021700390',
 '0021700386',
 '0021700386',
 '0021700387',
 '0021700387',
 '0021700385',
 '0021700385',
 '0021700388',
 '0021700388',
 '0021700389',
 '0021700389',
 '0021700395',
 '0021700395',
 '0021700391',
 '0021700391',
 '0021700396',
 '0021700396',
 '0021700392',
 '0021700392',
 '0021700393',
 '0021700393',
 '0021700394',
 '0021700394',
 '0021700399',
 '0021700399',
 '0021700400',
 '0021700400',
 '0021700397',
 '0021700397',
 '0021700398',
 '0021700398',
 '0021700402',
 '0021700402',
 '0021700403',
 '0021700403',
 '0021700401',
 '0021700401',
 '0021700409',
 '0021700409',
 '0021700411',
 '0021700411',
 '0021700407',
 '0021700407',
 '0021700405',
 '0021700405',
 '0021700412',
 '0021700412',
 '0021700408',
 '0021700408',
 '0021700404',
 '0021700404',
 '0021700406',
 '0021700406',
 '0021700410',
 '0021700410',
 '0021700417',
 '0021700417',
 '0021700414',
 '0021700414',
 '0021700415',
 '0021700415',
 '0021700413',
 '0021700413',
 '0021700416',
 '0021700416',
 '0021700421',
 '0021700421',
 '0021700423',
 '0021700423',
 '0021700420',
 '0021700420',
 '0021700428',
 '0021700428',
 '0021700426',
 '0021700426',
 '0021700419',
 '0021700419',
 '0021700427',
 '0021700427',
 '0021700418',
 '0021700418',
 '0021700422',
 '0021700422',
 '0021700424',
 '0021700424',
 '0021700425',
 '0021700425',
 '0021700435',
 '0021700435',
 '0021700431',
 '0021700431',
 '0021700433',
 '0021700433',
 '0021700430',
 '0021700430',
 '0021700432',
 '0021700432',
 '0021700429',
 '0021700429',
 '0021700434',
 '0021700434',
 '0021700436',
 '0021700436',
 '0021700439',
 '0021700439',
 '0021700438',
 '0021700438',
 '0021700437',
 '0021700437',
 '0021700440',
 '0021700440',
 '0021700449',
 '0021700449',
 '0021700450',
 '0021700450',
 '0021700444',
 '0021700444',
 '0021700445',
 '0021700445',
 '0021700442',
 '0021700442',
 '0021700443',
 '0021700443',
 '0021700448',
 '0021700448',
 '0021700446',
 '0021700446',
 '0021700441',
 '0021700441',
 '0021700447',
 '0021700447',
 '0021700451',
 '0021700451',
 '0021700453',
 '0021700453',
 '0021700452',
 '0021700452',
 '0021700464',
 '0021700464',
 '0021700458',
 '0021700458',
 '0021700457',
 '0021700457',
 '0021700456',
 '0021700456',
 '0021700465',
 '0021700465',
 '0021700459',
 '0021700459',
 '0021700463',
 '0021700463',
 '0021700455',
 '0021700455',
 '0021700461',
 '0021700461',
 '0021700462',
 '0021700462',
 '0021700454',
 '0021700454',
 '0021700460',
 '0021700460',
 '0021700467',
 '0021700467',
 '0021700468',
 '0021700468',
 '0021700469',
 '0021700469',
 '0021700466',
 '0021700466',
 '0021700470',
 '0021700470',
 '0021700479',
 '0021700479',
 '0021700473',
 '0021700473',
 '0021700472',
 '0021700472',
 '0021700475',
 '0021700475',
 '0021700474',
 '0021700474',
 '0021700471',
 '0021700471',
 '0021700476',
 '0021700476',
 '0021700478',
 '0021700478',
 '0021700477',
 '0021700477',
 '0021700489',
 '0021700489',
 '0021700491',
 '0021700491',
 '0021700490',
 '0021700490',
 '0021700485',
 '0021700485',
 '0021700486',
 '0021700486',
 '0021700488',
 '0021700488',
 '0021700482',
 '0021700482',
 '0021700484',
 '0021700484',
 '0021700492',
 '0021700492',
 '0021700481',
 '0021700481',
 '0021700483',
 '0021700483',
 '0021700480',
 '0021700480',
 '0021700487',
 '0021700487',
 '0021700494',
 '0021700494',
 '0021700497',
 '0021700497',
 '0021700493',
 '0021700493',
 '0021700495',
 '0021700495',
 '0021700496',
 '0021700496',
 '0021700502',
 '0021700502',
 '0021700504',
 '0021700504',
 '0021700505',
 '0021700505',
 ...]

In [320]:
# read in schedule and extract games of specific season for estimation
df_schedule = pd.read_csv(data_path + "schedule.csv", dtype={'GAME_ID':str})
list_game_ids = df_schedule[df_schedule['SEASON_ID'] == 22020]['GAME_ID'].to_list()

# subset
subs = subs[subs['GAME_ID'].isin(list_game_id)]
data = data[data['GAME_ID'].isin(list_game_id)]
starters = starters[starters['GAME_ID'].isin(list_game_id)]

['0022000001',
 '0022000001',
 '0022000002',
 '0022000002',
 '0022000003',
 '0022000003',
 '0022000013',
 '0022000013',
 '0022000017',
 '0022000017',
 '0022000018',
 '0022000018',
 '0022000015',
 '0022000015',
 '0022000019',
 '0022000019',
 '0022000020',
 '0022000020',
 '0022000004',
 '0022000004',
 '0022000012',
 '0022000012',
 '0022000011',
 '0022000011',
 '0022000010',
 '0022000010',
 '0022000014',
 '0022000014',
 '0022000005',
 '0022000005',
 '0022000006',
 '0022000006',
 '0022000007',
 '0022000007',
 '0022000008',
 '0022000008',
 '0022000009',
 '0022000009',
 '0022000027',
 '0022000027',
 '0022000026',
 '0022000026',
 '0022000025',
 '0022000025',
 '0022000023',
 '0022000023',
 '0022000029',
 '0022000029',
 '0022000028',
 '0022000028',
 '0022000030',
 '0022000030',
 '0022000022',
 '0022000022',
 '0022000024',
 '0022000024',
 '0022000021',
 '0022000021',
 '0022000040',
 '0022000040',
 '0022000038',
 '0022000038',
 '0022000036',
 '0022000036',
 '0022000031',
 '0022000031',
 '0022000035',
 '0022000035',
 '0022000037',
 '0022000037',
 '0022000039',
 '0022000039',
 '0022000032',
 '0022000032',
 '0022000033',
 '0022000033',
 '0022000034',
 '0022000034',
 '0022000045',
 '0022000045',
 '0022000042',
 '0022000042',
 '0022000041',
 '0022000041',
 '0022000044',
 '0022000044',
 '0022000043',
 '0022000043',
 '0022000049',
 '0022000049',
 '0022000053',
 '0022000053',
 '0022000054',
 '0022000054',
 '0022000046',
 '0022000046',
 '0022000051',
 '0022000051',
 '0022000047',
 '0022000047',
 '0022000048',
 '0022000048',
 '0022000055',
 '0022000055',
 '0022000050',
 '0022000050',
 '0022000052',
 '0022000052',
 '0022000060',
 '0022000060',
 '0022000056',
 '0022000056',
 '0022000057',
 '0022000057',
 '0022000061',
 '0022000061',
 '0022000058',
 '0022000058',
 '0022000059',
 '0022000059',
 '0022000064',
 '0022000064',
 '0022000065',
 '0022000065',
 '0022000068',
 '0022000068',
 '0022000062',
 '0022000062',
 '0022000063',
 '0022000063',
 '0022000066',
 '0022000066',
 '0022000067',
 '0022000067',
 '0022000078',
 '0022000078',
 '0022000075',
 '0022000075',
 '0022000072',
 '0022000072',
 '0022000070',
 '0022000070',
 '0022000073',
 '0022000073',
 '0022000077',
 '0022000077',
 '0022000071',
 '0022000071',
 '0022000076',
 '0022000076',
 '0022000074',
 '0022000074',
 '0022000069',
 '0022000069',
 '0022000082',
 '0022000082',
 '0022000081',
 '0022000081',
 '0022000079',
 '0022000079',
 '0022000080',
 '0022000080',
 '0022000083',
 '0022000083',
 '0022000084',
 '0022000084',
 '0022000092',
 '0022000092',
 '0022000089',
 '0022000089',
 '0022000090',
 '0022000090',
 '0022000091',
 '0022000091',
 '0022000086',
 '0022000086',
 '0022000085',
 '0022000085',
 '0022000088',
 '0022000088',
 '0022000087',
 '0022000087',
 '0022000094',
 '0022000094',
 '0022000101',
 '0022000101',
 '0022000093',
 '0022000093',
 '0022000098',
 '0022000098',
 '0022000096',
 '0022000096',
 '0022000099',
 '0022000099',
 '0022000095',
 '0022000095',
 '0022000097',
 '0022000097',
 '0022000100',
 '0022000100',
 '0022000102',
 '0022000102',
 '0022000105',
 '0022000105',
 '0022000106',
 '0022000106',
 '0022000104',
 '0022000104',
 '0022000103',
 '0022000103',
 '0022000116',
 '0022000116',
 '0022000109',
 '0022000109',
 '0022000112',
 '0022000112',
 '0022000115',
 '0022000115',
 '0022000108',
 '0022000108',
 '0022000111',
 '0022000111',
 '0022000113',
 '0022000113',
 '0022000107',
 '0022000107',
 '0022000110',
 '0022000110',
 '0022000117',
 '0022000117',
 '0022000114',
 '0022000114',
 '0022000121',
 '0022000121',
 '0022000118',
 '0022000118',
 '0022000122',
 '0022000122',
 '0022000120',
 '0022000120',
 '0022000119',
 '0022000119',
 '0022000130',
 '0022000130',
 '0022000131',
 '0022000131',
 '0022000125',
 '0022000125',
 '0022000124',
 '0022000124',
 '0022000127',
 '0022000127',
 '0022000123',
 '0022000123',
 '0022000129',
 '0022000129',
 '0022000132',
 '0022000132',
 '0022000128',
 '0022000128',
 '0022000126',
 '0022000126',
 '0022000133',
 '0022000133',
 '0022000137',
 '0022000137',
 '0022000135',
 '0022000135',
 '0022000139',
 '0022000139',
 '0022000140',
 '0022000140',
 '0022000138',
 '0022000138',
 '0022000134',
 '0022000134',
 '0022000136',
 '0022000136',
 '0022000148',
 '0022000148',
 '0022000144',
 '0022000144',
 '0022000143',
 '0022000143',
 '0022000142',
 '0022000142',
 '0022000146',
 '0022000146',
 '0022000141',
 '0022000141',
 '0022000147',
 '0022000147',
 '0022000151',
 '0022000151',
 '0022000150',
 '0022000150',
 '0022000155',
 '0022000155',
 '0022000153',
 '0022000153',
 '0022000156',
 '0022000156',
 '0022000149',
 '0022000149',
 '0022000152',
 '0022000152',
 '0022000157',
 '0022000157',
 '0022000163',
 '0022000163',
 '0022000158',
 '0022000158',
 '0022000161',
 '0022000161',
 '0022000159',
 '0022000159',
 '0022000162',
 '0022000162',
 '0022000168',
 '0022000168',
 '0022000172',
 '0022000172',
 '0022000165',
 '0022000165',
 '0022000173',
 '0022000173',
 '0022000169',
 '0022000169',
 '0022000164',
 '0022000164',
 '0022000170',
 '0022000170',
 '0022000174',
 '0022000174',
 '0022000176',
 '0022000176',
 '0022000178',
 '0022000178',
 '0022000177',
 '0022000177',
 '0022000175',
 '0022000175',
 '0022000187',
 '0022000187',
 '0022000180',
 '0022000180',
 '0022000181',
 '0022000181',
 '0022000182',
 '0022000182',
 '0022000186',
 '0022000186',
 '0022000188',
 '0022000188',
 '0022000184',
 '0022000184',
 '0022000189',
 '0022000189',
 '0022000190',
 '0022000190',
 '0022000192',
 '0022000192',
 '0022000195',
 '0022000195',
 '0022000191',
 '0022000191',
 '0022000193',
 '0022000193',
 '0022000196',
 '0022000196',
 '0022000202',
 '0022000202',
 '0022000201',
 '0022000201',
 '0022000198',
 '0022000198',
 '0022000200',
 '0022000200',
 '0022000212',
 '0022000212',
 '0022000211',
 '0022000211',
 '0022000203',
 '0022000203',
 '0022000209',
 '0022000209',
 '0022000206',
 '0022000206',
 '0022000207',
 '0022000207',
 '0022000205',
 '0022000205',
 '0022000210',
 '0022000210',
 '0022000208',
 '0022000208',
 '0022000214',
 '0022000214',
 '0022000213',
 '0022000213',
 '0022000218',
 '0022000218',
 '0022000223',
 '0022000223',
 '0022000224',
 '0022000224',
 '0022000222',
 '0022000222',
 '0022000216',
 '0022000216',
 '0022000217',
 '0022000217',
 '0022000219',
 '0022000219',
 '0022000221',
 '0022000221',
 '0022000220',
 '0022000220',
 '0022000228',
 '0022000228',
 '0022000226',
 '0022000226',
 '0022000227',
 '0022000227',
 '0022000233',
 '0022000233',
 '0022000237',
 '0022000237',
 '0022000238',
 '0022000238',
 '0022000239',
 '0022000239',
 '0022000232',
 '0022000232',
 '0022000230',
 '0022000230',
 '0022000231',
 '0022000231',
 '0022000241',
 '0022000241',
 '0022000236',
 '0022000236',
 '0022000229',
 '0022000229',
 '0022000234',
 '0022000234',
 '0022000245',
 '0022000245',
 '0022000248',
 '0022000248',
 '0022000244',
 '0022000244',
 '0022000243',
 '0022000243',
 '0022000242',
 '0022000242',
 '0022000247',
 '0022000247',
 '0022000246',
 '0022000246',
 '0022000253',
 '0022000253',
 '0022000250',
 '0022000250',
 '0022000251',
 '0022000251',
 '0022000252',
 '0022000252',
 '0022000256',
 '0022000256',
 '0022000254',
 '0022000254',
 '0022000249',
 '0022000249',
 '0022000266',
 '0022000266',
 '0022000262',
 '0022000262',
 '0022000260',
 '0022000260',
 '0022000259',
 '0022000259',
 '0022000261',
 '0022000261',
 '0022000257',
 '0022000257',
 '0022000267',
 '0022000267',
 '0022000258',
 '0022000258',
 '0022000265',
 '0022000265',
 '0022000269',
 '0022000269',
 '0022000270',
 '0022000270',
 '0022000268',
 '0022000268',
 '0022000276',
 '0022000276',
 '0022000283',
 '0022000283',
 '0022000280',
 '0022000280',
 '0022000281',
 '0022000281',
 '0022000273',
 '0022000273',
 '0022000272',
 '0022000272',
 '0022000275',
 '0022000275',
 '0022000282',
 '0022000282',
 '0022000274',
 '0022000274',
 '0022000271',
 '0022000271',
 '0022000277',
 '0022000277',
 '0022000279',
 '0022000279',
 '0022000286',
 '0022000286',
 '0022000287',
 '0022000287',
 '0022000285',
 '0022000285',
 '0022000284',
 '0022000284',
 '0022000296',
 '0022000296',
 '0022000291',
 '0022000291',
 '0022000289',
 '0022000289',
 '0022000297',
 '0022000297',
 '0022000294',
 '0022000294',
 '0022000288',
 '0022000288',
 '0022000290',
 '0022000290',
 '0022000292',
 '0022000292',
 '0022000293',
 '0022000293',
 '0022000295',
 '0022000295',
 '0022000305',
 '0022000305',
 '0022000304',
 '0022000304',
 '0022000298',
 '0022000298',
 '0022000302',
 '0022000302',
 '0022000301',
 '0022000301',
 '0022000303',
 '0022000303',
 '0022000299',
 '0022000299',
 '0022000300',
 '0022000300',
 '0022000308',
 '0022000308',
 '0022000307',
 '0022000307',
 '0022000306',
 '0022000306',
 '0022000311',
 '0022000311',
 '0022000310',
 '0022000310',
 '0022000309',
 '0022000309',
 '0022000320',
 '0022000320',
 '0022000315',
 '0022000315',
 '0022000312',
 '0022000312',
 '0022000314',
 '0022000314',
 '0022000316',
 '0022000316',
 '0022000313',
 '0022000313',
 '0022000319',
 '0022000319',
 '0022000317',
 '0022000317',
 '0022000318',
 '0022000318',
 '0022000326',
 '0022000326',
 '0022000324',
 '0022000324',
 '0022000323',
 '0022000323',
 '0022000325',
 '0022000325',
 '0022000322',
 '0022000322',
 '0022000559',
 '0022000559',
 '0022000334',
 '0022000334',
 '0022000332',
 '0022000332',
 '0022000328',
 '0022000328',
 '0022000331',
 '0022000331',
 '0022000329',
 '0022000329',
 '0022000330',
 '0022000330',
 '0022000336',
 '0022000336',
 '0022000327',
 '0022000327',
 '0022000333',
 '0022000333',
 '0022000335',
 '0022000335',
 '0022000337',
 '0022000337',
 '0022000341',
 '0022000341',
 '0022000338',
 '0022000338',
 '0022000339',
 '0022000339',
 '0022000340',
 '0022000340',
 '0022000349',
 '0022000349',
 '0022000345',
 '0022000345',
 '0022000350',
 '0022000350',
 '0022000344',
 '0022000344',
 '0022000346',
 '0022000346',
 '0022000347',
 '0022000347',
 '0022000343',
 '0022000343',
 '0022000342',
 '0022000342',
 '0022000348',
 '0022000348',
 '0022000354',
 '0022000354',
 '0022000361',
 '0022000361',
 '0022000351',
 '0022000351',
 '0022000353',
 '0022000353',
 '0022000358',
 '0022000358',
 '0022000357',
 '0022000357',
 '0022000356',
 '0022000356',
 '0022000360',
 '0022000360',
 '0022000352',
 '0022000352',
 '0022000359',
 '0022000359',
 '0022000355',
 '0022000355',
 '0022000364',
 '0022000364',
 '0022000365',
 '0022000365',
 '0022000366',
 '0022000366',
 '0022000363',
 '0022000363',
 '0022000215',
 '0022000215',
 '0022000371',
 '0022000371',
 '0022000374',
 '0022000374',
 '0022000368',
 '0022000368',
 '0022000372',
 '0022000372',
 '0022000370',
 '0022000370',
 '0022000373',
 '0022000373',
 '0022000367',
 '0022000367',
 '0022000369',
 '0022000369',
 '0022000378',
 '0022000378',
 '0022000376',
 '0022000376',
 '0022000375',
 '0022000375',
 '0022000380',
 '0022000380',
 '0022000379',
 '0022000379',
 '0022000381',
 '0022000381',
 '0022000377',
 '0022000377',
 '0022000390',
 '0022000390',
 '0022000385',
 '0022000385',
 '0022000389',
 '0022000389',
 '0022000383',
 '0022000383',
 '0022000384',
 '0022000384',
 '0022000388',
 '0022000388',
 '0022000387',
 '0022000387',
 '0022000382',
 '0022000382',
 '0022000386',
 '0022000386',
 '0022000393',
 '0022000393',
 '0022000398',
 '0022000398',
 '0022000392',
 '0022000392',
 '0022000391',
 '0022000391',
 '0022000394',
 '0022000394',
 '0022000403',
 '0022000403',
 '0022000400',
 '0022000400',
 '0022000412',
 '0022000412',
 '0022000404',
 '0022000404',
 '0022000402',
 '0022000402',
 '0022000397',
 '0022000397',
 '0022000399',
 '0022000399',
 '0022000405',
 '0022000405',
 '0022000401',
 '0022000401',
 '0022000395',
 '0022000395',
 '0022000396',
 '0022000396',
 '0022000409',
 '0022000409',
 '0022000408',
 '0022000408',
 '0022000406',
 '0022000406',
 '0022000410',
 '0022000410',
 '0022000407',
 '0022000407',
 '0022000417',
 '0022000417',
 '0022000419',
 '0022000419',
 '0022000561',
 '0022000561',
 '0022000411',
 '0022000411',
 '0022000418',
 '0022000418',
 '0022000416',
 '0022000416',
 '0022000414',
 '0022000414',
 '0022000560',
 '0022000560',
 '0022000413',
 '0022000413',
 '0022000415',
 '0022000415',
 '0022000424',
 '0022000424',
 '0022000422',
 '0022000422',
 '0022000425',
 '0022000425',
 '0022000423',
 '0022000423',
 '0022000420',
 '0022000420',
 '0022000426',
 '0022000426',
 '0022000421',
 '0022000421',
 '0022000433',
 '0022000433',
 '0022000427',
 '0022000427',
 '0022000430',
 '0022000430',
 '0022000431',
 '0022000431',
 '0022000432',
 '0022000432',
 '0022000429',
 '0022000429',
 '0022000439',
 '0022000439',
 '0022000443',
 '0022000443',
 '0022000564',
 '0022000564',
 '0022000438',
 '0022000438',
 '0022000444',
 '0022000444',
 '0022000436',
 '0022000436',
 '0022000440',
 '0022000440',
 '0022000437',
 '0022000437',
 '0022000562',
 '0022000562',
 '0022000441',
 '0022000441',
 '0022000446',
 '0022000446',
 '0022000445',
 '0022000445',
 '0022000447',
 '0022000447',
 '0022000450',
 '0022000450',
 '0022000451',
 '0022000451',
 '0022000457',
 '0022000457',
 '0022000449',
 '0022000449',
 '0022000563',
 '0022000563',
 '0022000453',
 '0022000453',
 '0022000454',
 '0022000454',
 '0022000452',
 '0022000452',
 '0022000455',
 '0022000455',
 '0022000463',
 '0022000463',
 '0022000460',
 '0022000460',
 '0022000464',
 '0022000464',
 '0022000459',
 '0022000459',
 '0022000462',
 '0022000462',
 '0022000469',
 '0022000469',
 '0022000472',
 '0022000472',
 '0022000467',
 '0022000467',
 '0022000466',
 '0022000466',
 '0022000471',
 '0022000471',
 '0022000470',
 '0022000470',
 '0022000468',
 '0022000468',
 '0022000465',
 '0022000465',
 '0022000479',
 '0022000479',
 '0022000477',
 '0022000477',
 '0022000474',
 '0022000474',
 '0022000478',
 '0022000478',
 '0022000476',
 '0022000476',
 '0022000475',
 '0022000475',
 '0022000483',
 '0022000483',
 '0022000482',
 '0022000482',
 '0022000488',
 '0022000488',
 '0022000481',
 '0022000481',
 '0022000480',
 '0022000480',
 '0022000486',
 '0022000486',
 '0022000485',
 '0022000485',
 '0022000487',
 '0022000487',
 '0022000484',
 '0022000484',
 '0022000493',
 '0022000493',
 '0022000496',
 '0022000496',
 '0022000491',
 '0022000491',
 '0022000492',
 '0022000492',
 '0022000497',
 '0022000497',
 '0022000489',
 '0022000489',
 '0022000490',
 '0022000490',
 '0022000495',
 '0022000495',
 '0022000494',
 '0022000494',
 '0022000498',
 '0022000498',
 '0022000500',
 '0022000500',
 '0022000499',
 '0022000499',
 '0022000503',
 '0022000503',
 '0022000502',
 '0022000502',
 '0022000501',
 '0022000501',
 '0022000511',
 '0022000511',
 '0022000512',
 '0022000512',
 '0022000508',
 '0022000508',
 '0022000505',
 '0022000505',
 '0022000507',
 '0022000507',
 '0022000504',
 '0022000504',
 '0022000506',
 '0022000506',
 '0022000510',
 '0022000510',
 '0022000509',
 '0022000509',
 '0022000513',
 '0022000513',
 '0022000514',
 '0022000514',
 '0022000515',
 '0022000515',
 '0022000519',
 '0022000519',
 '0022000516',
 '0022000516',
 '0022000517',
 '0022000517',
 '0022000518',
 '0022000518',
 '0022000527',
 '0022000527',
 '0022000524',
 '0022000524',
 '0022000525',
 '0022000525',
 '0022000522',
 '0022000522',
 '0022000521',
 '0022000521',
 '0022000520',
 '0022000520',
 '0022000528',
 '0022000528',
 ...]

In [95]:
subs

,Unnamed: 0,GAME_ID,stint,game_time_left,TEAM_LOCATION,PLAYER_OUT_ID,PLAYER_IN_ID
0,559,0021800001,1,1644.0,AWAY,203967.0,101161.0
1,560,0021800001,2,1644.0,AWAY,203954.0,200755.0
2,570,0021800001,3,1436.0,HOME,1628369.0,202694.0
3,571,0021800001,4,1436.0,HOME,202330.0,1626179.0
4,589,0021800001,5,1068.0,AWAY,203496.0,204456.0
...,...,...,...,...,...,...,...
157482,1535409,0022001080,48,40.0,AWAY,203469.0,202687.0
157483,1535415,0022001080,49,20.0,HOME,201577.0,1630264.0
157484,1535416,0022001080,50,20.0,AWAY,1629023.0,1628984.0
157485,1535417,0022001080,51,20.0,AWAY,1629667.0,1630163.0
157486,1535418,0022001080,52,20.0,AWAY,202687.0,203469.0

In [96]:
starters

,Unnamed: 0,START_POSITION,PLAYER_ID,GAME_ID,TEAM_ID,TEAM_LOCATION,STARTER
0,0,F,202331.0,0021800002,1610612760,AWAY,True
1,1,F,202335.0,0021800002,1610612760,AWAY,True
2,2,C,203500.0,0021800002,1610612760,AWAY,True
3,3,G,1628390.0,0021800002,1610612760,AWAY,True
4,4,G,203471.0,0021800002,1610612760,AWAY,True
...,...,...,...,...,...,...,...
33615,15,F,1630230.0,0022001072,1610612740,HOME,True
33616,16,F,201949.0,0022001072,1610612740,HOME,True
33617,17,C,1626195.0,0022001072,1610612740,HOME,True
33618,18,G,202339.0,0022001072,1610612740,HOME,True
33619,19,G,1629638.0,0022001072,1610612740,HOME,True

In [164]:
# create player role vector
n_games = starters['GAME_ID'].unique().shape[0]
naming_vector = ['GUARD_1_HOME', 'GUARD_2_HOME', 'FORWARD_1_HOME', 'FORWARD_2_HOME', 'CENTER_1_HOME', 'GUARD_1_AWAY', 'GUARD_2_AWAY', 'FORWARD_1_AWAY', 'FORWARD_2_AWAY', 'CENTER_1_AWAY']
player_role_vec = naming_vector * n_games

# insert into starters
starters = starters.sort_values(['GAME_ID', 'TEAM_LOCATION', 'START_POSITION'], ascending=False)
starters['PLAYER_ROLE'] = player_role_vec

df = pd.pivot_table(starters, values='PLAYER_ID', index=['GAME_ID'], columns=['PLAYER_ROLE'], aggfunc=np.sum).reset_index()

naming_vector.append('GAME_ID')
df = df[naming_vector]

In [165]:
df

PLAYER_ROLE,GUARD_1_HOME,GUARD_2_HOME,FORWARD_1_HOME,FORWARD_2_HOME,CENTER_1_HOME,GUARD_1_AWAY,GUARD_2_AWAY,FORWARD_1_AWAY,FORWARD_2_AWAY,CENTER_1_AWAY,GAME_ID
0,1627759.0,202681.0,1628369.0,202330.0,201143.0,1628365.0,1627732.0,203967.0,203496.0,203954.0,0021800001
1,202691.0,201939.0,201142.0,203110.0,1627745.0,1628390.0,203471.0,202331.0,202335.0,203500.0,0021800002
2,203087.0,202689.0,201587.0,101107.0,203469.0,1627763.0,202339.0,203114.0,203507.0,201572.0,0021800003
3,1628971.0,202704.0,1628379.0,201933.0,203083.0,1627747.0,1626156.0,203925.0,201162.0,1628386.0,0021800004
4,203506.0,201954.0,202711.0,201152.0,1626167.0,202066.0,201144.0,202718.0,203210.0,201188.0,0021800005
...,...,...,...,...,...,...,...,...,...,...,...
3357,203468.0,203081.0,1626181.0,203496.0,203994.0,203085.0,1630267.0,1629008.0,203932.0,203999.0,0022001076
3358,1627741.0,1626153.0,1629663.0,1629002.0,1627745.0,204060.0,201144.0,202711.0,1626220.0,203497.0,0022001077
3359,1629022.0,1627749.0,201942.0,1629640.0,1627751.0,1628975.0,1626166.0,1628969.0,1630188.0,203967.0,0022001078
3360,1627761.0,1630201.0,1626169.0,1630273.0,203920.0,203200.0,1627747.0,203926.0,1629052.0,1627734.0,0022001079
3361,203078.0,201566.0,202722.0,1629060.0,203458.0,1626179.0,1630163.0,1628970.0,1629667.0,1629023.0,0022001080

In [90]:
starters

,Unnamed: 0,START_POSITION,PLAYER_ID,GAME_ID,TEAM_ID,TEAM_LOCATION,STARTER,PLAYER_ROLE
33588,18,G,203078.0,0022001080,1610612764,HOME,True,GUARD_1_HOME
33589,19,G,201566.0,0022001080,1610612764,HOME,True,GUARD_2_HOME
33585,15,F,202722.0,0022001080,1610612764,HOME,True,FORWARD_1_HOME
33586,16,F,1629060.0,0022001080,1610612764,HOME,True,FORWARD_2_HOME
33587,17,C,203458.0,0022001080,1610612764,HOME,True,CENTER_1_HOME
...,...,...,...,...,...,...,...,...
13,3,G,1628365.0,0021800001,1610612755,AWAY,True,GUARD_1_AWAY
14,4,G,1627732.0,0021800001,1610612755,AWAY,True,GUARD_2_AWAY
10,0,F,203967.0,0021800001,1610612755,AWAY,True,FORWARD_1_AWAY
11,1,F,203496.0,0021800001,1610612755,AWAY,True,FORWARD_2_AWAY
12,2,C,203954.0,0021800001,1610612755,AWAY,True,CENTER_1_AWAY

In [178]:
from tqdm import tqdm

naming_vector2 = ['GUARD_1_HOME', 'GUARD_2_HOME', 'FORWARD_1_HOME', 'FORWARD_2_HOME', 'CENTER_1_HOME', 'GUARD_1_AWAY', 'GUARD_2_AWAY', 'FORWARD_1_AWAY', 'FORWARD_2_AWAY', 'CENTER_1_AWAY']
game_ids = df['GAME_ID'].unique()

list_dfs = list()
print("Create on court dataset: \n")
for i, game in enumerate(tqdm(game_ids)):

    # get game id and starters
    game_id = df.iloc[i,-1]
    starter_i = df.iloc[i,:-1].values

    # get subs in that game
    subs_game = subs[subs['GAME_ID'] == game]
    tmp = subs_game

    # extract substitutions
    players_out = subs_game['PLAYER_OUT_ID'].values
    players_in = subs_game['PLAYER_IN_ID'].values

    # get stints
    stints_game = subs_game['stint'].values
    list_oncourt = list()

    for s, stint in enumerate(stints_game):

        # first stint: starters on the court
        if stint == 1:
            on_court_s = starter_i

        # append on court
        list_oncourt.append(on_court_s)    

        # replace players
        on_court_s[on_court_s == players_out[s]] = players_in[s]
    
    # create dataframe for game
    tmp_on_court = pd.DataFrame(np.concatenate(list_oncourt, axis=0).reshape(-1, 10), columns=naming_vector2)
    tmp_on_court['stint'] = stints_game
    tmp_on_court['GAME_ID'] = game
    
    # collect
    list_dfs.append(tmp_on_court)

# create df for all games
df_on_court = pd.concat(list_dfs)

100%|██████████| 3362/3362 [00:30<00:00, 112.01it/s]

In [179]:
df_on_court

,GUARD_1_HOME,GUARD_2_HOME,FORWARD_1_HOME,FORWARD_2_HOME,CENTER_1_HOME,GUARD_1_AWAY,GUARD_2_AWAY,FORWARD_1_AWAY,FORWARD_2_AWAY,CENTER_1_AWAY,stint,GAME_ID
0,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,1,0021800001
1,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,2,0021800001
2,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,3,0021800001
3,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,4,0021800001
4,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,5,0021800001
...,...,...,...,...,...,...,...,...,...,...,...,...
47,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,48,0022001080
48,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,49,0022001080
49,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,50,0022001080
50,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,51,0022001080
51,202397.0,1629060.0,203078.0,202397.0,201566.0,1626179.0,203469.0,203469.0,1626179.0,1626179.0,52,0022001080

In [184]:
df_all = pd.merge(data, df_on_court)

In [300]:
def stints_to_dummy_simple(data, df_on_court):
    
    data_stints = pd.merge(data, df_on_court)
    
    # seperate the scores
    scores = data_stints[['GAME_ID', 'stint', 'HOME_PTS', 'AWAY_PTS', 'HOME_PM', 'HOME_PM_100']]
    
    # home and away names
    home_names = ['GUARD_1_HOME', 'GUARD_2_HOME', 'FORWARD_1_HOME', 'FORWARD_2_HOME', 'CENTER_1_HOME']
    away_names = ['GUARD_1_AWAY', 'GUARD_2_AWAY', 'FORWARD_1_AWAY', 'FORWARD_2_AWAY', 'CENTER_1_AWAY']
    all_names = ['GUARD_1_HOME', 'GUARD_2_HOME', 'FORWARD_1_HOME', 'FORWARD_2_HOME', 'CENTER_1_HOME', 'GUARD_1_AWAY', 'GUARD_2_AWAY', 'FORWARD_1_AWAY', 'FORWARD_2_AWAY', 'CENTER_1_AWAY']

    # shift into long format, id: game_id & stint - value vars home and away
    tmp = pd.melt(data_stints, id_vars=['GAME_ID', 'stint'], value_vars=all_names)
    
    # get the dummies on the long format
    tmp2 = pd.get_dummies(tmp, columns=['value'], prefix="", prefix_sep="")
    
    # create boolean and factor vector
    bool_away = tmp2['variable'].isin(away_names)
    weight_vec = np.where(bool_away, -1, 1).reshape(-1, 1)
    
    # extract dummy matrix
    tmp_a = np.asarray(tmp2.iloc[:, 3:])
    
    # adjust for home and away
    tmp_b = tmp_a * weight_vec
    
    # replace
    tmp2.iloc[:, 3:] = tmp_b
    
    # merge scores and players
    df = pd.merge(scores, tmp2)
    
    # get series objects to track the players and their "position"
    series_location_player = pd.Series(df.columns[7:].values)
    series_id_player = series_location_player.apply(lambda x: x.replace('.0', ''))
    series_id_player = series_id_player.astype(int)

    return df, series_id_player

In [301]:
tmp, tmpid = stints_to_dummy_simple(data_stints=df_all.iloc[0:20000,:])

In [363]:
from rapm_toolbox import *
subs = pd.read_csv("subs.csv", dtype={'GAME_ID':str})
starter = pd.read_csv("starters.csv", dtype={'GAME_ID':str})

In [362]:
starter

,Unnamed: 0,START_POSITION,PLAYER_ID,GAME_ID,TEAM_ID,TEAM_LOCATION,STARTER
0,0,F,202331.0,0021800002,1610612760,AWAY,True
1,1,F,202335.0,0021800002,1610612760,AWAY,True
2,2,C,203500.0,0021800002,1610612760,AWAY,True
3,3,G,1628390.0,0021800002,1610612760,AWAY,True
4,4,G,203471.0,0021800002,1610612760,AWAY,True
...,...,...,...,...,...,...,...
33615,15,F,1630230.0,0022001072,1610612740,HOME,True
33616,16,F,201949.0,0022001072,1610612740,HOME,True
33617,17,C,1626195.0,0022001072,1610612740,HOME,True
33618,18,G,202339.0,0022001072,1610612740,HOME,True
33619,19,G,1629638.0,0022001072,1610612740,HOME,True

In [361]:
subs

,Unnamed: 0,GAME_ID,stint,game_time_left,TEAM_LOCATION,PLAYER_OUT_ID,PLAYER_IN_ID
0,559,0021800001,1,1644.0,AWAY,203967.0,101161.0
1,560,0021800001,2,1644.0,AWAY,203954.0,200755.0
2,570,0021800001,3,1436.0,HOME,1628369.0,202694.0
3,571,0021800001,4,1436.0,HOME,202330.0,1626179.0
4,589,0021800001,5,1068.0,AWAY,203496.0,204456.0
...,...,...,...,...,...,...,...
157482,1535409,0022001080,48,40.0,AWAY,203469.0,202687.0
157483,1535415,0022001080,49,20.0,HOME,201577.0,1630264.0
157484,1535416,0022001080,50,20.0,AWAY,1629023.0,1628984.0
157485,1535417,0022001080,51,20.0,AWAY,1629667.0,1630163.0
157486,1535418,0022001080,52,20.0,AWAY,202687.0,203469.0

In [388]:
# create player role vector
n_games = starters['GAME_ID'].unique().shape[0]
naming_vector = ['GUARD_1_HOME', 'GUARD_2_HOME', 'FORWARD_1_HOME', 'FORWARD_2_HOME', 'CENTER_1_HOME', 'GUARD_1_AWAY', 'GUARD_2_AWAY', 'FORWARD_1_AWAY', 'FORWARD_2_AWAY', 'CENTER_1_AWAY']
player_role_vec = naming_vector * n_games

# insert into starters
starters = starters.sort_values(['GAME_ID', 'TEAM_LOCATION', 'START_POSITION'], ascending=False)
starters['PLAYER_ROLE'] = player_role_vec

# transform to wide format
df = pd.pivot_table(starters, values='PLAYER_ID', index=['GAME_ID'], columns=['PLAYER_ROLE'], aggfunc=np.sum).reset_index()

# rename
naming_vector.append('GAME_ID')
df = df[naming_vector]

naming_vector2 = ['GUARD_1_HOME', 'GUARD_2_HOME', 'FORWARD_1_HOME', 'FORWARD_2_HOME', 'CENTER_1_HOME', 'GUARD_1_AWAY', 'GUARD_2_AWAY', 'FORWARD_1_AWAY', 'FORWARD_2_AWAY', 'CENTER_1_AWAY']
game_ids = df['GAME_ID'].unique()

list_dfs = list()
print("Create on court dataset: \n")

for i, game in enumerate(tqdm(game_ids[0:1])):

    # get game id and starters
    game_id = df.iloc[i,-1]
    starter_i = df.iloc[i,:-1].values

    # get subs in that game
    subs_game = subs[subs['GAME_ID'] == game]
    tmp = subs_game

    # extract substitutions
    players_out = subs_game['PLAYER_OUT_ID'].values
    players_in = subs_game['PLAYER_IN_ID'].values

    # get stints
    stints_game = subs_game['stint'].values
    list_oncourt = list()

    for s, stint in enumerate(stints_game):
        
        # first stint: starters on the court
        if s == 0:
            on_court_s = starter_i
        
        # append on court
        list_oncourt.append(on_court_s)    

        # replace players
        on_court_s[on_court_s == players_out[s]] = players_in[s]
        print(on_court_s)

    # create dataframe for game
    tmp_on_court = pd.DataFrame(np.concatenate(list_oncourt, axis=0).reshape(-1, 10), columns=naming_vector2)
    tmp_on_court['stint'] = stints_game
    tmp_on_court['GAME_ID'] = game

    # collect
    list_dfs.append(tmp_on_court)

    # create df for all games
    df_on_court = pd.concat(list_dfs)

100%|██████████| 1/1 [00:00<00:00, 74.07it/s]

Create on court dataset:

[1627759.0 202681.0 1628369.0 202330.0 201143.0 1628365.0 1627732.0
 101161.0 203496.0 203954.0]
[1627759.0 202681.0 1628369.0 202330.0 201143.0 1628365.0 1627732.0
 101161.0 203496.0 200755.0]
[1627759.0 202681.0 202694.0 202330.0 201143.0 1628365.0 1627732.0
 101161.0 203496.0 200755.0]
[1627759.0 202681.0 202694.0 1626179.0 201143.0 1628365.0 1627732.0
 101161.0 203496.0 200755.0]
[1627759.0 202681.0 202694.0 1626179.0 201143.0 1628365.0 1627732.0
 101161.0 204456.0 200755.0]
[1627759.0 203935.0 202694.0 1626179.0 201143.0 1628365.0 1627732.0
 101161.0 204456.0 200755.0]
[1627759.0 203935.0 202694.0 1626179.0 201143.0 1628365.0 1627732.0
 203954.0 204456.0 200755.0]
[1628369.0 203935.0 202694.0 1626179.0 201143.0 1628365.0 1627732.0
 203954.0 204456.0 200755.0]
[1628369.0 203935.0 202694.0 1626179.0 203382.0 1628365.0 1627732.0
 203954.0 204456.0 200755.0]
[1628369.0 203935.0 202694.0 1626179.0 203382.0 203967.0 1627732.0
 203954.0 204456.0 200755.0]
[1628369.0 203935.0 202694.0 1626179.0 203382.0 1627732.0 1627732.0
 203954.0 204456.0 200755.0]
[1628369.0 203935.0 202694.0 1626179.0 203382.0 1627732.0 1627732.0
 203954.0 1629013.0 200755.0]
[1628369.0 203935.0 202694.0 1626179.0 203382.0 1627732.0 1627732.0
 203954.0 1629013.0 203496.0]
[201143.0 203935.0 202694.0 1626179.0 203382.0 1627732.0 1627732.0
 203954.0 1629013.0 203496.0]
[201143.0 203935.0 202694.0 202681.0 203382.0 1627732.0 1627732.0 203954.0
 1629013.0 203496.0]
[201143.0 203935.0 202694.0 202681.0 203382.0 1627732.0 1627732.0 203954.0
 1629013.0 203496.0]
[201143.0 203935.0 202694.0 202681.0 202694.0 1627732.0 1627732.0 203954.0
 1629013.0 203496.0]
[201143.0 203935.0 202694.0 202681.0 202694.0 1627732.0 1627732.0 101161.0
 1629013.0 203496.0]
[201143.0 203935.0 202694.0 202681.0 202694.0 1627732.0 1627732.0 101161.0
 203954.0 203496.0]
[201143.0 203935.0 202694.0 202681.0 202694.0 1627732.0 1627732.0 200755.0
 203954.0 203496.0]
[201143.0 203935.0 1626179.0 202681.0 1626179.0 1627732.0 1627732.0
 200755.0 203954.0 203496.0]
[201143.0 1628369.0 1626179.0 202681.0 1626179.0 1627732.0 1627732.0
 200755.0 203954.0 203496.0]
[201143.0 1628369.0 1626179.0 202681.0 1626179.0 1627732.0 1627732.0
 200755.0 203954.0 203496.0]
[201143.0 1628369.0 1626179.0 202681.0 1626179.0 1627732.0 1627732.0
 200755.0 203954.0 203496.0]
[201143.0 1628369.0 1626179.0 202681.0 1626179.0 1627732.0 1627732.0
 200755.0 101161.0 203496.0]
[201143.0 1628369.0 1626179.0 202681.0 1626179.0 1627732.0 1627732.0
 200755.0 101161.0 203496.0]
[201143.0 1628369.0 1626179.0 203935.0 1626179.0 1627732.0 1627732.0
 200755.0 101161.0 203496.0]
[1628464.0 1628369.0 1626179.0 203935.0 1626179.0 1627732.0 1627732.0
 200755.0 101161.0 203496.0]
[1628464.0 1628369.0 1626179.0 203935.0 1626179.0 1627732.0 1627732.0
 1629013.0 101161.0 203496.0]
[1628464.0 1628369.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 1629013.0 101161.0 203496.0]
[1628464.0 1628369.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 1629013.0 101161.0 203967.0]
[1628464.0 202694.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 1629013.0 101161.0 203967.0]
[203382.0 202694.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 1629013.0 101161.0 203967.0]
[203382.0 202694.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 1629013.0 203954.0 203967.0]
[203382.0 202694.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 1629013.0 203954.0 203496.0]
[203382.0 202694.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 200755.0 203954.0 203496.0]
[203382.0 202694.0 1626179.0 203935.0 1626179.0 1628365.0 1628365.0
 200755.0 203954.0 203496.0]
[203382.0 202694.0 202330.0 203935.0 202330.0 1628365.0 1628365.0 200755.0
 203954.0 203496.0]
[201143.0 202694.0 202330.0 203935.0 202330.0 1628365.0 1628365.0 200755.0
 203954.0 203496.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 200755.0 203954.0 203496.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 200755.0 203954.0 1629013.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 200755.0 203954.0 1629013.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 200755.0 203954.0 204456.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 200755.0 203954.0 204456.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 1629013.0 203954.0 204456.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 1629013.0 203954.0 200755.0]
[201143.0 1628369.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 203496.0 203954.0 200755.0]
[201143.0 1628464.0 202330.0 203935.0 202330.0 1628365.0 1628365.0
 203496.0 203954.0 200755.0]
[201143.0 1628464.0 1628400.0 203935.0 1628400.0 1628365.0 1628365.0
 203496.0 203954.0 200755.0]
[1627824.0 1628464.0 1628400.0 203935.0 1628400.0 1628365.0 1628365.0
 203496.0 203954.0 200755.0]
[1627824.0 1628464.0 1628400.0 203935.0 1628400.0 1628365.0 1628365.0
 203496.0 203954.0 200755.0]
[1627824.0 1628464.0 1628400.0 203935.0 1628400.0 1628365.0 1628365.0
 203496.0 101161.0 200755.0]
[1627824.0 1628464.0 1628400.0 203935.0 1628400.0 1628365.0 1628365.0
 203496.0 101161.0 1628413.0]
[1627824.0 1628464.0 1628400.0 203935.0 1628400.0 1628365.0 1628365.0
 1627788.0 101161.0 1628413.0]
[1627824.0 1628464.0 1628400.0 202954.0 1628400.0 1628365.0 1628365.0
 1627788.0 101161.0 1628413.0]
[1627824.0 1628464.0 1628400.0 202954.0 1628400.0 1628365.0 1628365.0
 1627788.0 101161.0 1628413.0]

*PROBLEM: Player gets subbed in who is already on the court. This "destroys" the whole chain afterwards.*

In [379]:
starter[starter['GAME_ID'] == "0021800001"]

,Unnamed: 0,START_POSITION,PLAYER_ID,GAME_ID,TEAM_ID,TEAM_LOCATION,STARTER
10,0,F,203967.0,0021800001,1610612755,AWAY,True
11,1,F,203496.0,0021800001,1610612755,AWAY,True
12,2,C,203954.0,0021800001,1610612755,AWAY,True
13,3,G,1628365.0,0021800001,1610612755,AWAY,True
14,4,G,1627732.0,0021800001,1610612755,AWAY,True
15,13,F,1628369.0,0021800001,1610612738,HOME,True
16,14,F,202330.0,0021800001,1610612738,HOME,True
17,15,C,201143.0,0021800001,1610612738,HOME,True
18,16,G,1627759.0,0021800001,1610612738,HOME,True
19,17,G,202681.0,0021800001,1610612738,HOME,True

In [381]:
df[df['GAME_ID'] == "0021800001"]

PLAYER_ROLE,GUARD_1_HOME,GUARD_2_HOME,FORWARD_1_HOME,FORWARD_2_HOME,CENTER_1_HOME,GUARD_1_AWAY,GUARD_2_AWAY,FORWARD_1_AWAY,FORWARD_2_AWAY,CENTER_1_AWAY,GAME_ID
0,1627759.0,202681.0,1628369.0,202330.0,201143.0,1628365.0,1627732.0,203967.0,203496.0,203954.0,0021800001

In [378]:
subs[subs['GAME_ID'] == "0021800001"]

,Unnamed: 0,GAME_ID,stint,game_time_left,TEAM_LOCATION,PLAYER_OUT_ID,PLAYER_IN_ID
0,559,0021800001,1,1644.0,AWAY,203967.0,101161.0
1,560,0021800001,2,1644.0,AWAY,203954.0,200755.0
2,570,0021800001,3,1436.0,HOME,1628369.0,202694.0
3,571,0021800001,4,1436.0,HOME,202330.0,1626179.0
4,589,0021800001,5,1068.0,AWAY,203496.0,204456.0
5,596,0021800001,6,908.0,HOME,202681.0,203935.0
6,597,0021800001,7,908.0,AWAY,101161.0,203954.0
7,606,0021800001,8,692.0,HOME,1627759.0,1628369.0
8,607,0021800001,9,692.0,HOME,201143.0,203382.0
9,608,0021800001,10,692.0,AWAY,1628365.0,203967.0
10,642,0021800001,11,1941.0,AWAY,203967.0,1627732.0
11,657,0021800001,12,1698.0,AWAY,204456.0,1629013.0
12,658,0021800001,13,1698.0,AWAY,200755.0,203496.0
13,682,0021800001,14,1191.0,HOME,1628369.0,201143.0
14,683,0021800001,15,1191.0,HOME,1626179.0,202681.0
15,684,0021800001,16,1191.0,HOME,202330.0,1627759.0
16,685,0021800001,17,1191.0,HOME,203382.0,202694.0
17,686,0021800001,18,1191.0,AWAY,203954.0,101161.0
18,707,0021800001,19,738.0,AWAY,1629013.0,203954.0
19,708,0021800001,20,738.0,AWAY,101161.0,200755.0
20,737,0021800001,21,234.0,HOME,202694.0,1626179.0
21,738,0021800001,22,234.0,HOME,203935.0,1628369.0
22,784,0021800001,23,986.0,AWAY,203967.0,204456.0
23,794,0021800001,24,802.0,HOME,203382.0,202330.0
24,807,0021800001,25,644.0,AWAY,203954.0,101161.0
25,808,0021800001,26,644.0,HOME,1627759.0,1626179.0
26,809,0021800001,27,644.0,HOME,202681.0,203935.0
27,821,0021800001,28,468.0,HOME,201143.0,1628464.0
28,822,0021800001,29,468.0,AWAY,200755.0,1629013.0
29,829,0021800001,30,386.0,AWAY,1627732.0,1628365.0
30,830,0021800001,31,386.0,AWAY,203496.0,203967.0
31,833,0021800001,32,382.0,HOME,1628369.0,202694.0
32,847,0021800001,33,146.0,HOME,1628464.0,203382.0
33,848,0021800001,34,146.0,AWAY,101161.0,203954.0
34,857,0021800001,35,90.0,AWAY,203967.0,203496.0
35,874,0021800001,36,657.0,AWAY,1629013.0,200755.0
36,894,0021800001,37,532.0,AWAY,204456.0,203967.0
37,901,0021800001,38,479.0,HOME,1626179.0,202330.0
38,905,0021800001,39,454.0,HOME,203382.0,201143.0
39,919,0021800001,40,359.0,HOME,202694.0,1628369.0
40,920,0021800001,41,359.0,AWAY,203496.0,1629013.0
41,921,0021800001,42,359.0,HOME,1627759.0,203935.0
42,927,0021800001,43,344.0,AWAY,1629013.0,204456.0
43,943,0021800001,44,268.0,HOME,202681.0,1626179.0
44,944,0021800001,45,268.0,AWAY,200755.0,1629013.0
45,953,0021800001,46,187.0,AWAY,204456.0,200755.0
46,954,0021800001,47,187.0,AWAY,1629013.0,203496.0
47,972,0021800001,48,87.0,HOME,1628369.0,1628464.0
48,973,0021800001,49,87.0,HOME,202330.0,1628400.0
49,974,0021800001,50,87.0,HOME,201143.0,1627824.0
50,975,0021800001,51,87.0,AWAY,203967.0,204456.0
51,976,0021800001,52,87.0,AWAY,203954.0,101161.0
52,977,0021800001,53,87.0,AWAY,200755.0,1628413.0
53,978,0021800001,54,87.0,AWAY,203496.0,1627788.0
54,986,0021800001,55,49.0,HOME,203935.0,202954.0
55,987,0021800001,56,49.0,AWAY,1627732.0,1629013.0

In [377]:
df_on_court

,GUARD_1_HOME,GUARD_2_HOME,FORWARD_1_HOME,FORWARD_2_HOME,CENTER_1_HOME,GUARD_1_AWAY,GUARD_2_AWAY,FORWARD_1_AWAY,FORWARD_2_AWAY,CENTER_1_AWAY,stint,GAME_ID
0,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,1,0021800001
1,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,2,0021800001
2,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,3,0021800001
3,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,4,0021800001
4,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,5,0021800001
5,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,6,0021800001
6,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,7,0021800001
7,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,8,0021800001
8,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,9,0021800001
9,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,10,0021800001
10,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,11,0021800001
11,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,12,0021800001
12,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,13,0021800001
13,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,14,0021800001
14,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,15,0021800001
15,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,16,0021800001
16,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,17,0021800001
17,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,18,0021800001
18,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,19,0021800001
19,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,20,0021800001
20,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,21,0021800001
21,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,22,0021800001
22,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,23,0021800001
23,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,24,0021800001
24,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,25,0021800001
25,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,26,0021800001
26,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,27,0021800001
27,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,28,0021800001
28,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,29,0021800001
29,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,30,0021800001
30,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,31,0021800001
31,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,32,0021800001
32,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,33,0021800001
33,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,34,0021800001
34,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,35,0021800001
35,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,36,0021800001
36,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,37,0021800001
37,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,38,0021800001
38,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,39,0021800001
39,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,40,0021800001
40,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,41,0021800001
41,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,42,0021800001
42,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,43,0021800001
43,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,44,0021800001
44,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,45,0021800001
45,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,46,0021800001
46,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,47,0021800001
47,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,48,0021800001
48,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,49,0021800001
49,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,50,0021800001
50,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,51,0021800001
51,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,52,0021800001
52,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,53,0021800001
53,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,54,0021800001
54,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,55,0021800001
55,1627824.0,1628464.0,1628400.0,202954.0,1628400.0,1628365.0,1628365.0,1627788.0,101161.0,1628413.0,56,0021800001

In [374]:
subs

,Unnamed: 0,GAME_ID,stint,game_time_left,TEAM_LOCATION,PLAYER_OUT_ID,PLAYER_IN_ID
0,559,0021800001,1,1644.0,AWAY,203967.0,101161.0
1,560,0021800001,2,1644.0,AWAY,203954.0,200755.0
2,570,0021800001,3,1436.0,HOME,1628369.0,202694.0
3,571,0021800001,4,1436.0,HOME,202330.0,1626179.0
4,589,0021800001,5,1068.0,AWAY,203496.0,204456.0
...,...,...,...,...,...,...,...
157482,1535409,0022001080,48,40.0,AWAY,203469.0,202687.0
157483,1535415,0022001080,49,20.0,HOME,201577.0,1630264.0
157484,1535416,0022001080,50,20.0,AWAY,1629023.0,1628984.0
157485,1535417,0022001080,51,20.0,AWAY,1629667.0,1630163.0
157486,1535418,0022001080,52,20.0,AWAY,202687.0,203469.0

In [390]:
pbp = pd.read_csv("pbp_16_20.csv", dtype={'GAME_ID':str})

In [397]:
pbp[pbp['GAME_ID'] == "0021800001"]

,Unnamed: 0,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
1121621,0,0021800001,2.0,12.0,0.0,1.0,8:03 PM,12:00,NaN,Start of 1st Period (8:03 PM EST),...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0
1121622,1,0021800001,4.0,10.0,0.0,1.0,8:03 PM,12:00,Jump Ball Horford vs. Embiid: Tip to Simmons,NaN,...,76ers,PHI,5.0,1627732.0,Ben Simmons,1.610613e+09,Philadelphia,76ers,PHI,1
1121623,2,0021800001,7.0,2.0,1.0,1.0,8:03 PM,11:40,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1
1121624,3,0021800001,8.0,4.0,0.0,1.0,8:04 PM,11:40,CELTICS Rebound,NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0
1121625,4,0021800001,10.0,2.0,1.0,1.0,8:04 PM,11:15,MISS Tatum 25' 3PT Jump Shot,NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1122108,487,0021800001,704.0,4.0,0.0,4.0,10:21 PM,0:46,Ojeleye REBOUND (Off:0 Def:1),NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1
1122109,488,0021800001,708.0,1.0,6.0,4.0,10:21 PM,0:38,Wanamaker 1' Driving Layup (2 PTS),NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1
1122110,489,0021800001,709.0,2.0,63.0,4.0,10:21 PM,0:22,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1
1122111,490,0021800001,710.0,4.0,0.0,4.0,10:22 PM,0:19,Wanamaker REBOUND (Off:0 Def:1),NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1
1122112,491,0021800001,711.0,13.0,0.0,4.0,10:22 PM,0:00,NaN,End of 4th Period (10:22 PM EST),...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1

In [395]:
pbp.columns

Index(['Unnamed: 0', 'GAME_ID', 'EVENTNUM', 'EVENTMSGTYPE',
       'EVENTMSGACTIONTYPE', 'PERIOD', 'WCTIMESTRING', 'PCTIMESTRING',
       'HOMEDESCRIPTION', 'NEUTRALDESCRIPTION', 'VISITORDESCRIPTION', 'SCORE',
       'SCOREMARGIN', 'PERSON1TYPE', 'PLAYER1_ID', 'PLAYER1_NAME',
       'PLAYER1_TEAM_ID', 'PLAYER1_TEAM_CITY', 'PLAYER1_TEAM_NICKNAME',
       'PLAYER1_TEAM_ABBREVIATION', 'PERSON2TYPE', 'PLAYER2_ID',
       'PLAYER2_NAME', 'PLAYER2_TEAM_ID', 'PLAYER2_TEAM_CITY',
       'PLAYER2_TEAM_NICKNAME', 'PLAYER2_TEAM_ABBREVIATION', 'PERSON3TYPE',
       'PLAYER3_ID', 'PLAYER3_NAME', 'PLAYER3_TEAM_ID', 'PLAYER3_TEAM_CITY',
       'PLAYER3_TEAM_NICKNAME', 'PLAYER3_TEAM_ABBREVIATION',
       'VIDEO_AVAILABLE_FLAG'],
      dtype='object')

In [399]:
pbp[(pbp['GAME_ID'] == "0021800001") & (pbp['EVENTMSGTYPE'] == 8)][['PERIOD', 'EVENTNUM', 'PLAYER1_ID', 'PLAYER2_ID', 'HOMEDESCRIPTION', 'NEUTRALDESCRIPTION', 'VISITORDESCRIPTION']].reset_index()

,index,PERIOD,EVENTNUM,PLAYER1_ID,PLAYER2_ID,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION
0,1121670,1.0,67.0,203967.0,101161.0,NaN,NaN,SUB: Johnson FOR Saric
1,1121671,1.0,68.0,203954.0,200755.0,NaN,NaN,SUB: Redick FOR Embiid
2,1121681,1.0,84.0,1628369.0,202694.0,SUB: Morris Sr. FOR Tatum,NaN,NaN
3,1121682,1.0,85.0,202330.0,1626179.0,SUB: Rozier FOR Hayward,NaN,NaN
4,1121700,1.0,109.0,203496.0,204456.0,NaN,NaN,SUB: McConnell FOR Covington
5,1121707,1.0,118.0,202681.0,203935.0,SUB: Smart FOR Irving,NaN,NaN
6,1121708,1.0,119.0,101161.0,203954.0,NaN,NaN,SUB: Embiid FOR Johnson
7,1121717,1.0,133.0,1627759.0,1628369.0,SUB: Tatum FOR Brown,NaN,NaN
8,1121718,1.0,134.0,201143.0,203382.0,SUB: Baynes FOR Horford,NaN,NaN
9,1121719,1.0,135.0,1628365.0,203967.0,NaN,NaN,SUB: Saric FOR Fultz
10,1121755,2.0,188.0,203967.0,1627732.0,NaN,NaN,SUB: Simmons FOR Saric
11,1121770,2.0,212.0,204456.0,1629013.0,NaN,NaN,SUB: Shamet FOR McConnell
12,1121771,2.0,213.0,200755.0,203496.0,NaN,NaN,SUB: Covington FOR Redick
13,1121795,2.0,242.0,1628369.0,201143.0,SUB: Horford FOR Tatum,NaN,NaN
14,1121796,2.0,243.0,1626179.0,202681.0,SUB: Irving FOR Rozier,NaN,NaN
15,1121797,2.0,244.0,202330.0,1627759.0,SUB: Brown FOR Hayward,NaN,NaN
16,1121798,2.0,245.0,203382.0,202694.0,SUB: Morris Sr. FOR Baynes,NaN,NaN
17,1121799,2.0,246.0,203954.0,101161.0,NaN,NaN,SUB: Johnson FOR Embiid
18,1121820,2.0,281.0,1629013.0,203954.0,NaN,NaN,SUB: Embiid FOR Shamet
19,1121821,2.0,282.0,101161.0,200755.0,NaN,NaN,SUB: Redick FOR Johnson
20,1121850,2.0,321.0,202694.0,1626179.0,SUB: Rozier FOR Morris Sr.,NaN,NaN
21,1121851,2.0,322.0,203935.0,1628369.0,SUB: Tatum FOR Smart,NaN,NaN
22,1121899,3.0,400.0,203967.0,204456.0,NaN,NaN,SUB: McConnell FOR Saric
23,1121909,3.0,414.0,203382.0,202330.0,SUB: Hayward FOR Baynes,NaN,NaN
24,1121922,3.0,431.0,203954.0,101161.0,NaN,NaN,SUB: Johnson FOR Embiid
25,1121923,3.0,433.0,1627759.0,1626179.0,SUB: Rozier FOR Brown,NaN,NaN
26,1121924,3.0,434.0,202681.0,203935.0,SUB: Smart FOR Irving,NaN,NaN
27,1121936,3.0,450.0,201143.0,1628464.0,SUB: Theis FOR Horford,NaN,NaN
28,1121937,3.0,451.0,200755.0,1629013.0,NaN,NaN,SUB: Shamet FOR Redick
29,1121945,3.0,462.0,1627732.0,1628365.0,NaN,NaN,SUB: Fultz FOR Simmons
30,1121946,3.0,463.0,203496.0,203967.0,NaN,NaN,SUB: Saric FOR Covington
31,1121949,3.0,469.0,1628369.0,202694.0,SUB: Morris Sr. FOR Tatum,NaN,NaN
32,1121963,3.0,488.0,1628464.0,203382.0,SUB: Baynes FOR Theis,NaN,NaN
33,1121964,3.0,489.0,101161.0,203954.0,NaN,NaN,SUB: Embiid FOR Johnson
34,1121973,3.0,501.0,203967.0,203496.0,NaN,NaN,SUB: Covington FOR Saric
35,1121993,4.0,533.0,1629013.0,200755.0,NaN,NaN,SUB: Redick FOR Shamet
36,1122013,4.0,562.0,204456.0,203967.0,NaN,NaN,SUB: Saric FOR McConnell
37,1122020,4.0,570.0,1626179.0,202330.0,SUB: Hayward FOR Rozier,NaN,NaN
38,1122024,4.0,578.0,203382.0,201143.0,SUB: Horford FOR Baynes,NaN,NaN
39,1122038,4.0,601.0,202694.0,1628369.0,SUB: Tatum FOR Morris Sr.,NaN,NaN
40,1122039,4.0,602.0,203496.0,1629013.0,NaN,NaN,SUB: Shamet FOR Covington
41,1122040,4.0,605.0,1627759.0,203935.0,SUB: Smart FOR Brown,NaN,NaN
42,1122046,4.0,614.0,1629013.0,204456.0,NaN,NaN,SUB: McConnell FOR Shamet
43,1122062,4.0,633.0,202681.0,1626179.0,SUB: Rozier FOR Irving,NaN,NaN
44,1122063,4.0,634.0,200755.0,1629013.0,NaN,NaN,SUB: Shamet FOR Redick
45,1122072,4.0,651.0,204456.0,200755.0,NaN,NaN,SUB: Redick FOR McConnell
46,1122073,4.0,652.0,1629013.0,203496.0,NaN,NaN,SUB: Covington FOR Shamet
47,1122091,4.0,676.0,1628369.0,1628464.0,SUB: Theis FOR Tatum,NaN,NaN
48,1122092,4.0,677.0,202330.0,1628400.0,SUB: Ojeleye FOR Hayward,NaN,NaN
49,1122093,4.0,678.0,201143.0,1627824.0,SUB: Yabusele FOR Horford,NaN,NaN
50,1122094,4.0,679.0,203967.0,204456.0,NaN,NaN,SUB: McConnell FOR Saric
51,1122095,4.0,680.0,203954.0,101161.0,NaN,NaN,SUB: Johnson FOR Embiid
52,1122096,4.0,681.0,200755.0,1628413.0,NaN,NaN,SUB: Bolden FOR Redick
53,1122097,4.0,682.0,203496.0,1627788.0,NaN,NaN,SUB: Korkmaz FOR Covington
54,1122105,4.0,699.0,203935.0,202954.0,SUB: Wanamaker FOR Smart,NaN,NaN
55,1122106,4.0,700.0,1627732.0,1629013.0,NaN,NaN,SUB: Shamet FOR Simmons

See line 2 and 16!

In [1102]:
schedule['SEASON_ID'].unique()

array([22014, 22015, 22016, 22017, 22018, 22019, 22020])

In [1105]:
schedule = pd.read_csv("./data/season_prediction/schedule.csv", dtype={'GAME_ID':str})

In [11]:
schedule

,Unnamed: 0,Unnamed: 0.1,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,is_home_game
0,0,0,22014,1610612742,DAL,Dallas Mavericks,0021400002,2014-10-28,DAL @ SAS,L,...,33,17,9,3,10,20,100,-1,1,False
1,1,1,22014,1610612759,SAS,San Antonio Spurs,0021400002,2014-10-28,SAS vs. DAL,W,...,38,23,5,3,21,20,101,1,1,True
2,2,2,22014,1610612747,LAL,Los Angeles Lakers,0021400003,2014-10-28,LAL vs. HOU,L,...,36,16,7,3,13,32,90,-18,1,True
3,3,3,22014,1610612745,HOU,Houston Rockets,0021400003,2014-10-28,HOU @ LAL,W,...,47,22,7,3,14,30,108,18,1,False
4,4,4,22014,1610612740,NOP,New Orleans Pelicans,0021400001,2014-10-28,NOP vs. ORL,W,...,62,20,10,17,9,17,101,17,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16573,2155,2155,22020,1610612761,TOR,Toronto Raptors,0022001079,2021-05-16,TOR vs. IND,L,...,48,21,8,3,12,12,113,-12,1,True
16574,2156,2156,22020,1610612746,LAC,LA Clippers,0022001074,2021-05-16,LAC @ OKC,L,...,44,17,8,3,3,14,112,-5,1,False
16575,2157,2157,22020,1610612760,OKC,Oklahoma City Thunder,0022001074,2021-05-16,OKC vs. LAC,W,...,54,20,1,12,15,11,117,5,1,True
16576,2158,2158,22020,1610612747,LAL,Los Angeles Lakers,0022001072,2021-05-16,LAL @ NOP,W,...,42,30,14,5,10,16,110,12,1,False
16577,2159,2159,22020,1610612740,NOP,New Orleans Pelicans,0022001072,2021-05-16,NOP vs. LAL,L,...,47,26,4,5,21,18,98,-12,1,True

In [775]:
starter = starter[starter['GAME_ID'] == game_id]

In [8]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [12]:
schedule = pd.read_csv("./data/season_prediction/schedule.csv", dtype={'GAME_ID':str})

from nba_api.stats.endpoints.gamerotation import GameRotation
game_id = "0022001079" #"0021800001"
call = GameRotation(game_id)

rotation = pd.concat(call.get_data_frames())

In [14]:
def generate_dummy(rotation, schedule, game_id):
    
    """ insert subseted rotation, schedule and the corresponding game id
    from rotation and schedule data arrive at data, starters, starting_lineup and subs
    """

    # extract home games
    home_game = schedule[['TEAM_ID', 'GAME_ID', 'is_home_game']]

    # extract in and out times
    out_times = np.sort(rotation['OUT_TIME_REAL'].unique()) # get all out times
    in_times = np.sort(rotation['OUT_TIME_REAL'].unique()) # get all in times

    assert np.all(out_times == in_times), "Out and In times do not correspond"

    # sub time and time post
    sub_time = out_times
    time_post = np.arange(1, len(sub_time) + 1)

    # helper
    tmp_tp = pd.DataFrame(data={'sub_time':sub_time, 'time_post':time_post})

    # add sub times and home game, create player name
    df = pd.merge(tmp_tp, rotation, left_on='sub_time', right_on='OUT_TIME_REAL')
    df = pd.merge(df, home_game)
    df['PLAYER_NAME'] = df['PLAYER_FIRST'] + " " + df['PLAYER_LAST']
    df['PLAYER_NAME'] = df['PLAYER_NAME'].apply(lambda x: x.replace(".","")) # clean up names

    # create starter column and sort
    df.loc[df['IN_TIME_REAL'] == 0, 'STARTER'] = True
    df.loc[df['IN_TIME_REAL'] != 0, 'STARTER'] = False
    df = df.sort_values(['IN_TIME_REAL', 'OUT_TIME_REAL'])

    # watch out for whole dataset
    df['obs_id'] = np.arange(1, df.shape[0] + 1)

    # seperate starters
    starter = df[df['STARTER']][['GAME_ID', 'PERSON_ID', 'TEAM_ID','PLAYER_NAME', 'TEAM_NAME', 'is_home_game']].sort_values(['TEAM_NAME', 'is_home_game'])

    # get starting lineup
    starter['PLAYER_ROLE'] = ['AWAY1', 'AWAY2', 'AWAY3', 'AWAY4', 'AWAY5', 'HOME1', 'HOME2', 'HOME3', 'HOME4', 'HOME5']
    starting_lineup = pd.pivot_table(starter, index=['GAME_ID'], columns=['PLAYER_ROLE'], values=['PLAYER_NAME'], aggfunc=np.sum).reset_index()

    # prepare subs
    tmp_subs = pd.melt(df[['IN_TIME_REAL', 'OUT_TIME_REAL', 'obs_id']], id_vars='obs_id')

    # get unique substitutions and create a map
    unique_times = tmp_subs['value'].unique()
    tmp = pd.Series(unique_times).factorize()
    df_dict_subs = pd.DataFrame({'sub_event':tmp[0], 'sub_time':tmp[1]})

    # melt only the two time vars
    id_cols = df.loc[:, (df.columns != 'IN_TIME_REAL') & (df.columns != 'OUT_TIME_REAL')].columns.to_list()
    df2 = pd.melt(df, id_vars=id_cols, value_vars=['IN_TIME_REAL', 'OUT_TIME_REAL'])

    # merge map back to dataframe
    df = pd.merge(df2, df_dict_subs, left_on='value', right_on='sub_time')
    df = df.drop(['sub_time_y'], axis=1)

    # link in sub and out sub
    tmp_s = df[['PERSON_ID', 'PLAYER_NAME', 'variable', 'sub_event']]
    tmp_s = pd.pivot(tmp_s, columns="variable", values="sub_event")
    tmp_s.columns = ['in_sub_event', 'out_sub_event']

    # concatenate back to dataframe
    df = pd.concat([df, tmp_s], axis=1)

    # subset subs dataset from df
    subs = df[['PERSON_ID', 'PLAYER_NAME', 'in_sub_event', 'out_sub_event']]

    # move from data, starters, starting_lineup and subs to dummy matrix with home away weights

    # get all the sub events per game
    sub_events = subs['out_sub_event'].unique()
    sub_events = sub_events[~np.isnan(sub_events)]

    # get last sub event
    last_event = np.max(sub_events)

    # transform the starting lineup to np array
    sl = np.asarray(starting_lineup.values.tolist()[0][1:])

    # init list
    list_lineups = list()

    # start with starting lineup
    list_lineups.append(sl)
    current_lineup = sl

    # loop over substituions
    for s, sub in enumerate(sub_events):

        if sub < last_event:
            # get subs in and subs out
            sub_out = subs[subs['out_sub_event'] == sub]['PLAYER_NAME'].to_numpy()
            sub_in = subs[subs['in_sub_event'] == sub]['PLAYER_NAME'].to_numpy()

            # substitute players
            current_lineup[np.isin(current_lineup, sub_out)] = sub_in

        list_lineups.append(current_lineup.copy())

    # placeholders
    colnames = ["P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10"]

    # adapt shape and create on_court dataframe
    arr_on_court = np.concatenate(list_lineups, axis=0).reshape(-1, 10)
    df_on_court = pd.DataFrame(arr_on_court, columns=colnames)
    df_on_court['stint'] = np.insert(sub_events, 0, 0, axis=0)
    df_on_court['GAME_ID'] = game_id

    # melt it
    df_on_court_long = pd.melt(df_on_court, id_vars=['GAME_ID', 'stint'])

    # seperate players who played in this game and get home game flag
    player_team = df[['PLAYER_NAME', 'TEAM_NAME', 'is_home_game']].drop_duplicates()

    # add to dataframe
    tmp = pd.merge(df_on_court_long, player_team, left_on='value', right_on='PLAYER_NAME', how='left')
    tmp = tmp[['PLAYER_NAME', 'is_home_game']].drop_duplicates()

    # transform to dummy matrix
    tmp_dummies = pd.get_dummies(df_on_court_long, columns=['value'], prefix='', prefix_sep='')
    tmp_dummies = tmp_dummies.drop(['variable'], axis=1)

    # groupby stint and sum up
    test = tmp_dummies.iloc[:, 1:].groupby('stint').sum().reset_index()

    # extract player names and store their index
    tmp_player = pd.DataFrame({'PLAYER_NAME':test.columns.tolist()})
    tmp_player = tmp_player.reset_index()
    tmp_player.columns = ['index_pos', 'PLAYER_NAME']

    # merge player and player team to create home away vector
    tmp_vec = pd.merge(tmp_player, player_team, how='left')
    tmp_vec['vector'] = np.where(tmp_vec['is_home_game'], 1, -1)
    tmp_vec = tmp_vec[tmp_vec['PLAYER_NAME'] != 'stint']

    # extract weight vector and dummy matrix
    vec_weight = tmp_vec['vector'].values
    mat_dummy = test.iloc[:, 1:].values

    # insert back into the dataframe
    test.iloc[:, 1:] = mat_dummy * vec_weight

    # add game id
    test['GAME_ID'] = game_id
    
    return test

100%|██████████| 23/23 [00:00<00:00, 1875.55it/s]

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from src_dsp.rapm_toolbox import *

# load schedule and all rotation data
schedule_all = pd.read_csv(data_path + "schedule.csv", dtype={'GAME_ID':str})
rotation_all = pd.read_csv(data_path + "gamerotation_16_20.csv", dtype={'GAME_ID':str})

# get the game ids in the rotation data
game_ids = rotation_all['GAME_ID'].unique()

# storage
list_dummys = list()

# loop over all game ids
for game in tqdm(game_ids):
    
    # subset for current game
    rotation = rotation_all[rotation_all['GAME_ID'] == game]
    schedule = schedule[schedule['GAME_ID'] == game]
    
    # call generate dummy function
    tmp = generate_dummy(rotation=rotation, schedule=schedule, game_id=game)

    # store in list
    list_dummys.append(tmp)

# concatenate list and store
df = pd.concat(list_dummys)
df.to_csv(data_path + "dummy_matrix_rotation.csv")